FAIMS/FAIMS3

e2e/src/test/java/org/fedarch/faims3/AstroSky.java, e2e/src/test/java/org/fedarch/faims3/android/TestPopulateForm.java, e2e/src/test/java/org/fedarch/faims3/android/TestStagingForm.java, src/dummyData.ts
Lake Mungo -> AstroSky (silly name to make it easy to refer to)
CSIRO Geochemistry -> NotParkes (because it's not the Parkes dish ;)
=> Use dummy names rather than actual project names in dummy data

bin/couchdb_initialisation.sh, src/buildconfig.ts, src/datamodel.ts, src/gui/components/observation/form.tsx, src/sync/index.ts, src/users.ts
@riniangreani This should fix your problem
@aidanfar0 This will likely conflict with what your doing, not sure if you want to merge this then rebase your stuff, or do the opposite, I'll leave that up to you.
=> Add Autoactivation

src/gui/components/observation/form.tsx
This prevents an error that occurs in nullCoalesce up to 2 seconds
after an observation is deleted, where the saving function attempts
to save the deleted data.
=> Observation form: clean up timeouts on unmount

src/gui/components/observation/form.tsx
to resolve confusion about the alpha level features
https://faimsproject.atlassian.net/browse/FAIMS3-25
=> Re-Label the 'Save/Add' button in the observation form

src/gui/components/loadingApp.tsx, src/gui/components/metadataRenderer.tsx, src/gui/components/observation/table.tsx, src/gui/components/project/card.tsx, src/gui/components/project/cardHeaderAction.tsx, src/gui/components/project/sync.tsx, src/gui/components/ui/breadcrumbs.tsx, src/gui/pages/home.tsx, src/gui/pages/index.tsx, src/gui/pages/observation-create.tsx, src/gui/pages/observation-list.tsx, src/gui/pages/observation.tsx, src/gui/pages/project-list.tsx, src/gui/pages/project.tsx
FAIMS3-234: adds styling for smaller devices. Alpha was predominantly designed for sizes tablet and up, but this PR adds in styling for smaller screens (down to around an iphone 6).
=> Mobile updates

src/gui/components/observation/form.tsx, src/gui/pages/index.tsx, src/gui/pages/observation-list.tsx
TODO: Figure out why it's flashing (double re-direct?)
=> Observation save and new

src/buildconfig.ts, src/gui/components/footer.tsx
For footer to better describe testing versions
I tested with `REACT_APP_COMMIT_VERSION="flibertygibbet" npm run serve` and it worked. I'll edit the wiki when this PR is accepted. If no environment variable it defaults to the generic "-dev"
=> Added REACT_APP_COMMIT_VERSION environment variable 

src/buildconfig.ts, src/gui/components/footer.tsx
@Denubis Can you check this works with whatever mechanism you were using to get the version (this works with the output from git describe --all).
=> Rearrange version to use git describe

src/App.tsx, src/constants/routes.tsx, src/gui/components/navbar.tsx, src/gui/pages/about-build.tsx, src/gui/pages/index.tsx
This should mean we can check how a particular app was built to track down possible issues (syncing, missing/extra projects, etc.)
=> Add page showing build configuration

e2e/src/test/java/org/fedarch/faims3/android/AndroidTest.java, e2e/src/test/java/org/fedarch/faims3/chrome/ChromeTest.java
Signed-off-by: riniangreani <rini.angreani@csiro.au>
=> e2e: turn on browserstack logs

src/gui/pages/about-build.tsx, src/sync/index.ts
Uses a full reload to redo initialisation (we could be smarter about
this, but this has the advantage of clearing any local state).
=> Add wipe and reset button

server_configs/dev.sh, src/gui/pages/about-build.tsx
Minor things, now the boolean configs appear.
=> Fix dev server config and show build config

src/gui/pages/about-build.tsx
This may be useful when testing refresh behaviour in apps (where's
there's no access to normal refresh buttons).
=> Add refresh button

src/gui/components/observation/table.tsx, src/gui/components/project/card.tsx
=> Fix for overflow of observation table covering sync button

src/gui/components/project/card.tsx, src/projectMetadata.ts
Possible cause of infinite loop
This reverts commit 84918ad36467bc3476b694aa0c4e0c81f61e097d.
=> Revert "Add a function that listens for metadata updates"

src/gui/components/observation/table.tsx
=> Sort by last updated date by default

src/gui/pages/home.tsx
https://faimsproject.atlassian.net/browse/FAIMS3-254
=> Fix the homepage not showing projects

src/data_storage/index.ts, src/data_storage/internals.ts, src/datamodel/core.ts, src/datamodel/database.ts, src/datamodel/ui.ts
@Denubis This is the first of the renaming PRs. I think AentValue is the closest in meaning to the use of datum, but it would be good to confirm.
=> Rename datum to aent_value (as per glossary)

LICENSE-TEMPLATE-FOR-SRC, src/datamodel/staging.ts, src/gui/components/record/form.tsx, src/sync/staging-observation.ts, src/sync/staging.ts
Moves logic for staging area into a new object and file, out of the ObservationForm
=> Staging refactor

src/gui/components/project/sync.tsx, src/sync/databases.ts, src/sync/events.ts, src/sync/initialize.ts, src/sync/process-initialization.ts, src/sync/sync-handler.ts, src/sync/sync-toggle.ts
This should fix any errors occuring when using dummy data, it should stop all network activity in dummy data mode
=> Dummy data sync fix

src/App.tsx, src/constants/routes.tsx, src/data_storage/merging.ts, src/datamodel/database.ts, src/datamodel/typesystem.ts, src/datamodel/ui.ts, src/dummyData.ts, src/gui/components/project/cardHeaderAction.tsx, src/gui/components/record/form.tsx, src/gui/pages/record-create.tsx, src/gui/pages/record.tsx, src/sync/staging-observation.ts, src/uiSpecification.test.ts, src/uiSpecification.ts
Stepper on top of forms, for a form with multiple sections
This is _rebased_ off of `variants` so Don't merge this until you rebase this off main first
=> Form sections

src/dummyData.ts
The type names should be joined via `::` not `:`.
=> Fix viewset/typenames in dummyData

src/data_storage/internals.ts, src/data_storage/queries.ts, src/datamodel/core.ts, src/datamodel/database.ts, src/datamodel/ui.ts, src/reportWebVitals.ts, src/utils/eqTestSupport.ts
This should be quite reasonable, the main interesting change is assuming that a record does not change its type (which I don't envision being a major issue).
=> Add function to find records of a specific type

package-lock.json, package.json, src/datamodel/autoincrement.ts, src/dummyData.ts, src/gui/components/record/form.tsx, src/gui/fields/TakePoint.tsx, src/gui/fields/radio.tsx, src/projectSpecification.ts, src/sync/process-initialization.ts, src/sync/staging-observation.ts, src/sync/staging.ts
catch clauses add :any where necessary, and a new error for FormControlProps was fixed
=> Fix things that typescript 4.4 requires

src/datamodel/ui.ts, src/gui/component_registry/bundle_components.ts, src/gui/component_registry/index.ts, src/gui/component_registry/internals.ts
@KateSHENG This lets you get all the registered components. I've also added a category field to group them, the values are a first guess as to what they should be, the FAIMS team probably will want to change them.
=> Add function to get all available components

package.json, src/dummyData.ts, src/gui/component_registry/bundle_components.ts, src/gui/fields/TakePhoto.tsx
Add field to take a photo/use a photo on the device.
This doesn't handle the saving-to-db part, that's handled by the attachment code.
=> Add TakePhoto

package-lock.json, package.json
=> Add react-dropzone

package-lock.json, package.json, src/data_storage/attachments.ts, src/datamodel/database.ts, src/dummyData.ts, src/gui/component_registry/bundle_components.ts, src/gui/fields/FileUploader.tsx
=> Add file uploader

package-lock.json, package.json
=> Add pouch-debug

src/buildconfig.ts, src/pouchdb_debug.d.ts, src/sync/index.ts, src/sync/initialize.ts
Based on #224, this was manually added, rather than rebasing, due to the
number of changes since then.
=> Add pouchdb debugging

src/App.tsx, src/constants/routes.tsx, src/data_storage/internals.ts, src/data_storage/queries.ts, src/gui/components/project/card.tsx, src/gui/components/project/cardHeaderAction.tsx, src/gui/components/record/table.tsx, src/gui/pages/project-search.tsx
This is a very basic search, uses pouch's find with regex.
=> Add search

src/datamodel/database.ts, src/gui/components/authentication/login_form.tsx, src/sync/connection.ts, src/sync/databases.ts, src/sync/process-initialization.ts, src/users.ts
Currently this needs testing with couchdb to confirm the token is being sent. Once this is complete, then the rest of the authentication will be handled at the couchdb and conductor ends.
=> Add authentication via JWT

src/datamodel/geo.ts, src/gui/fields/TakePoint.tsx
@Denubis @stevecassidy Does this match what you'd expect to get?
=> Update take point

src/buildconfig.ts, src/data_storage/attachments.ts, src/data_storage/internals.ts, src/datamodel/drafts.ts, src/gui/components/record/form.tsx, src/gui/pages/record-create.tsx, src/sync/draft-state.ts, src/sync/draft-storage.ts
Currently the attachment code does not do the necessary transformations to properly save to pouchdb, but the annotations should fully work.
=> Add annotations and attachments to drafts

Dockerfile
=> just cleaning up some of the lint atomist is suggesting.

src/data_storage/internals.ts, src/data_storage/listeners.ts, src/gui/components/project/card.tsx, src/gui/components/project/cardHeaderAction.tsx, src/gui/components/record/table.tsx, tsconfig.json
This should mean that if a hrid is available then it gets displayed.
=> Hopefully fix hrid not being displayed

src/gui/components/record/form.tsx, src/gui/pages/project-settings.tsx
Some small fixes to make the console more readable.
=> Fix errors

src/gui/components/authentication/cluster_card.tsx, src/gui/components/authentication/login_form.tsx, src/users.ts
Previously, there were 1000+ log messages a second.
=> Simplify login logic to avoid unneeded work

package.json, src/gui/component_registry/bundle_components.ts, src/gui/fields/TmpMapSettings.tsx
This won't pass until we add the new settings to the maps package.
UPDATE:
Because of circular deps, the settings are going in here for now.
=> Add settings for map component

src/datamodel/autoincrement.ts, src/datamodel/database.ts, src/dummyData.ts, src/gui/components/autoincrement/browse-form.tsx, src/gui/components/project/cardHeaderAction.tsx, src/gui/pages/autoincrement-browse.tsx
@Denubis Should fix the upload of a new project.
=> Avoid storing project_id unnecessarily

src/data_storage/index.ts
@KateSHENG This should work for the referencing.
=> Add HRID lookup from record id function

src/gui/pages/project-settings.tsx
=> not editable for meta data

src/buildconfig.ts, src/data_storage/index.ts, src/data_storage/internals.ts, src/databaseAccess.tsx, src/datamodel/autoincrement.ts, src/gui/components/project/CreateProjectCard.tsx, src/gui/components/project/RangeHeader.tsx, src/gui/components/project/cardHeaderAction.tsx, src/gui/components/project/data/ComponentSetting.tsx, src/gui/components/project/data/componenentSetting.tsx, src/gui/components/record/fields.tsx, src/gui/components/record/form.tsx, src/gui/fields/TakePhoto.tsx, src/gui/fields/TakePoint.tsx, src/projectMetadata.ts, src/projectSpecification.ts, src/sync/databases.ts, src/sync/draft-storage.ts, src/sync/index.ts, src/uiSpecification.ts, src/users.ts
This should include errors in the higher priority log messages, rather than hiding them in debug logs.
=> Add further context to logs

src/data_storage/internals.ts, src/data_storage/merging.ts, src/datamodel/core.ts, src/gui/components/dashboard/actions.tsx, src/gui/components/metadataRenderer.tsx, src/gui/components/project/cardHeaderAction.tsx, src/gui/components/record/table.tsx, src/gui/pouchHook.ts, src/sync/events.ts, src/sync/index.ts
First we point the datadb listener to datadb, rather than metadatadb. Next we make sure to call the project listener callback at least once, so changes are watched.
=> Fix syncing

src/gui/components/footer.tsx, src/gui/fields/FileUploader.tsx
=> fix footer and fileupload crassh app issue

src/gui/components/authentication/login_form.tsx, src/users.ts
The token for a cluster can be updated, and there's more information about the token in the logs.
=> Add more context to token

src/gui/components/record/table.tsx
This was disabled previously as "Dummy User" was displayed. Now that authentication is set up, users will appear correctly.
=> Show who created/last updated record

src/gui/components/authentication/login_form.tsx, src/sync/connection.ts, src/sync/process-initialization.ts, src/sync/sync-toggle.ts
This adds some logging to confirm that pouch is indeed sending the token, and refreshes the connection when the user receives/updates the token.
=> Fully connect token to pouch

src/gui/components/project/CreateProjectCard.tsx
This also adds more await points where it would appear they are needed.
@KateSHENG Can you have a look at this and see if this helps with the db issues you've been having?
=> Add more logging in project builder

src/gui/components/record/form.tsx
=> fix safari blank issue

src/gui/components/authentication/login_form.tsx
This isn't a long term solution, but lets see if it works in apps now.
=> Try using iframe for authentication

bin/getDescribeString.sh
=> fixing describestring

src/data_storage/attachments.ts, src/data_storage/index.ts, src/data_storage/internals.ts, src/sync/draft-storage.ts, src/sync/new-project.ts
This should make it much easier to distinguish what a particular uuid is
for/identifying.
=> Add labels to uuids

src/App.tsx, src/constants/privateRouter.tsx, src/gui/components/authentication/cluster_card.tsx, src/gui/components/authentication/login_form.tsx, src/gui/components/record/form.tsx, src/gui/components/record/table.tsx, src/gui/pages/index.tsx, src/gui/pages/signin.tsx
=> Check user

src/gui/components/project/card.tsx, src/gui/components/record/table.tsx
At some point filter_deleted was removed, put it back.
=> Hide deleted record again

src/gui/components/authentication/cluster_card.tsx
This might help with authentication problems in the app.
=> Add logout button

src/gui/fields/FileUploader.tsx
=> Delete file fix

src/App.tsx, src/constants/privateRouter.tsx, src/gui/components/navbar.tsx, src/gui/components/ui/breadcrumbs.tsx, src/gui/pages/home.tsx, src/gui/pages/index.tsx, src/gui/pages/project-list.tsx, src/gui/pages/project-search.tsx, src/gui/pages/project-settings.tsx, src/gui/pages/project.tsx, src/gui/pages/record-create.tsx, src/gui/pages/record.tsx
=> display username in app and improve home page

src/gui/components/authentication/cluster_card.tsx, src/users.ts
Previously this was only changing state, and not removing the existing
token.
=> Have logout wipe token and restart connections

src/App.tsx, src/buildconfig.ts, src/data_storage/attachments.ts, src/data_storage/index.ts, src/data_storage/internals.ts, src/data_storage/merging.ts, src/databaseAccess.tsx, src/gui/components/authentication/login_form.tsx, src/gui/components/project/card.tsx, src/gui/components/project/data/componenentSetting.tsx, src/gui/components/project/tabs/ProjectDesign.tsx, src/gui/components/record/form.tsx, src/gui/components/record/table.tsx, src/gui/fields/TemplatedStringField.tsx, src/gui/pouchHook.ts, src/sync/connection.ts, src/sync/draft-storage.ts, src/sync/index.ts, src/sync/process-initialization.ts, src/users.ts
I doubt this will slow things down, but just to rule this out.
=> Reduce the amount of logging running in production

src/gui/components/record/form.tsx
We did not do anything with the save promise, this now adds it to the
flow.
=> Make sure to wait for save

src/gui/components/record/draft_table.tsx, src/gui/components/record/fields.tsx
=> FAIMS-374: fix the draft issue 

package-lock.json, package.json
Signed-off-by: James Tocknell <aragilar@gmail.com>
=> cap serve was removed in capacitor 3, use serve

src/buildconfig.ts, src/gui/components/project/sync.tsx, src/gui/pages/about-build.tsx
This makes it easier to switch on and off the various debugging options,
and adds options to remove the wipe and minifauxton buttons.
The USE_REAL_DATA option is removed as we no longer use it.
=> Add more switches and remove old ones

src/gui/pages/record.tsx
=> fix bug 417

.github/workflows/human-app-build.yml, .github/workflows/pr-test-apk.yml
Trying to fix CI deploys for APKs
Also, disabling publishing github releases for latest-android now that we have google play infrastructure online.
=> moving both human and integration java to Java11 for gradle 7

.github/workflows/human-app-build.yml
=> making dev and testing apk zips different

package-lock.json, package.json
Sentry will be used to catch and handle errors such that we can view
them later.
=> Add sentry dependencies

src/gui/fields/TakePhoto.tsx
See FAIMS3-323 for more details. This does not close FAIMS3-323.
=> Add some more context to the white TakePhoto bar

src/gui/components/record/delete.tsx, src/gui/pages/record-create.tsx
=> add delete button for draft

src/gui/components/ui/Dialog.tsx, src/gui/fields/TakePhoto.tsx
=> fix photo cut issue for origin size and image list

src/data_storage/merging.ts, src/datamodel/database.ts
This will need additional modification based on what information we want to present to the UI.
=> Add function to get initial human merge info

src/gui/components/record/form.tsx
This will hopefully fix FAIMS3-378.
=> Try to manipulate promises to wait on draft

src/data_storage/internals.ts, src/databaseAccess.tsx, src/gui/components/record/form.tsx, src/sync/draft-state.ts, src/sync/process-initialization.ts, src/sync/state.ts
Hopefully this should fix some weirdness we sometime see.
=> Add more awaits/promise handling

src/App.tsx, src/buildconfig.ts, src/constants/privateRouter.tsx, src/users.ts
This is primarily for performance testing, to avoid the need to work with the OAuth flow to access DBs.
=> Allow controlling whether app get redirected to login

src/gui/pages/about-build.tsx
This should allow cleaning the cache of the service worker when desired.
=> Have wipe/refresh buttons remove service worker

src/data_storage/merging.ts
This allows for better display and ordering in the UI.
=> Add revision creation details to merge context

src/gui/components/record/view.tsx, src/gui/pages/record.tsx
Branch fix small issue for conflict UI
=> Fix conflict UI

src/gui/components/record/customtoolbar.tsx, src/gui/components/record/draft_table.tsx, src/gui/components/record/table.tsx
=> disable export in tool bar

src/gui/components/record/Annotation.tsx, src/gui/components/record/conflict/conflictbutton.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/conflict/conflictpanel.tsx, src/gui/components/record/conflict/conflictstyle.tsx
=> adjust space for conflict resolve tab card

android/app/capacitor.build.gradle, android/app/src/main/assets/capacitor.plugins.json, android/capacitor.settings.gradle, ios/App/Podfile, package-lock.json, package.json
I want to do some quick prodding on apple to check iOS information related to the plugin, but @Denubis did you want to take a quick look and confirm that this adds the correct behaviour (it's implied by the documentation that this should fix things, but this plugin also gives us additional control in case it not sufficient/we want to change things slightly).
This should fix FAIMS3-472.
=> Add @capacitor/app to handle android back button

src/gui/components/record/conflict/conflictDialog.tsx, src/gui/components/record/conflict/conflictbutton.tsx, src/gui/components/record/conflict/conflictdroplist.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/conflict/conflictform.tsx, src/gui/components/record/conflict/conflictpanel.tsx, src/gui/components/record/conflict/conflicttoolbar.tsx, src/gui/components/record/fields.tsx, src/gui/components/record/form.tsx, src/gui/components/record/view.tsx, src/gui/components/ui/Dialog.tsx, src/gui/fields/FileUploader.tsx, src/gui/fields/TakePhoto.tsx, src/gui/fields/radio.tsx, src/gui/pages/record-create.tsx, src/gui/pages/record.tsx
Fix issue and updates for Conflict UI
=> Conflict UI continue

src/gui/components/record/conflict/conflictDialog.tsx, src/gui/components/ui/Dialog.tsx
=> add status for helper

package-lock.json, package.json
New version uses MUI and Capacitor 3.
=> Bump map plugin version to 1.0.6

.github/workflows/human-app-build.yml, .github/workflows/integration_tests.yml, .github/workflows/license.yml, .github/workflows/pr-test-apk.yml, .github/workflows/pr-test-ios.yml, .github/workflows/unit_tests_linting_and_basic_building.yml
=> updating versions of all github actions runners

src/gui/component_registry/bundle_components.ts, src/gui/components/project/data/componenentSetting.tsx, src/gui/components/record/form.tsx, src/gui/fields/multiselect.tsx, src/gui/fields/selectadvanced.tsx, src/gui/pages/home.tsx
This branch is just beta version of basic feature of hierarchical vocabularies  pick
=> Faims3 284 as a field researcher i need to be able to use hierarchical vocabularies and other techniques for rapid vocabulary selection

.github/workflows/pr-test-ios.yml
=> continue on error for ios

src/gui/components/record/Annotation.tsx, src/gui/components/record/view.tsx
@KateSHENG This is what I was talking about in terms of grid layouts of FAIMS3-328
=> Fix grid spacing (FAIMS3-328)

src/data_storage/merging.test.ts, src/data_storage/merging.ts
=> Deleted and undeleted revisions should not merge

src/gui/components/project/data/componenentSetting.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/fields/BasicFieldSettings.tsx, src/gui/fields/TemplatedStringField.tsx, src/gui/pages/index.tsx
=> Tiny camelcase and grammar tweaks

src/gui/components/authentication/cluster_card.tsx, src/gui/components/project/tabs/ProjectSubmit.tsx, src/gui/pages/autoincrement-browse.tsx, src/gui/pages/autoincrement-edit.tsx
=> Added back button for auto-incrementer

src/gui/components/record/Annotation.tsx, src/gui/components/record/conflict/conflictDialog.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/conflict/conflictstyle.tsx, src/gui/components/record/view.tsx
=> adjst space in record form

src/gui/components/record/conflict/conflictbutton.tsx
=> switch icons in conflict panel

src/gui/components/alert.tsx
=> adjust alert and FAIMS3-512 to auto move success message

src/gui/pages/record.tsx
=> FAIMS3-518

src/gui/components/record/conflict/conflictDialog.tsx, src/gui/components/record/conflict/conflictform.tsx
=> FAIMS3-463 typo fixes

.github/workflows/google-play-build.yml, android/fastlane/Fastfile
Need to get this into main to run .github actions.
=> testing automated google play publishing

README.md
Signed-off-by: J5kinner <jonah.lee.skinner@gmail.com>
=> Updated readme with docker setup

android/fastlane/Fastfile
=> reverting debug mode, as its not signed

android/bin/deployFAIMSApps.sh, android/bin/deployFieldmarkToClosedTrack.sh, android/bin/mergeTagFromMain.sh, android/metadata/android/en-GB/changelogs/27626741.txt, android/metadata/android/en-GB/changelogs/27626849.txt, android/metadata/android/en-GB/changelogs/27626896.txt, android/metadata/android/en-GB/changelogs/27626932.txt
=> More strict tag checkout during builds rather than merges

.github/workflows/human-app-build.yml
=> hardcoding REACT_APP_LOGIN_TOKEN to a GH secret

.github/workflows/human-app-build.yml
=> moving ios test framework to selenium server

.github/workflows/human-app-build.yml, .github/workflows/nightly-android-testbuild.yml
=> bumping builder versions

.faimsWords.txt, .github/workflows/human-app-build.yml, src/gui/components/record/draft_table.tsx, src/gui/components/record/recordStepper.tsx, src/gui/pages/project.tsx
Adding padding 5 instead of 0 on md mode.
Adjusted some things around the stepper to reduce impact on client deployment.
=> Fixes towards FAIMS3-530

src/databaseAccess.tsx, src/datamodel/database.ts, src/datamodel/ui.ts, src/gui/components/authentication/cluster_card.tsx, src/gui/components/authentication/login_form.tsx, src/gui/pages/signin.tsx, src/sync/databases.ts, src/users.ts
@Denubis This will require a slight change in the format of the docs in your upload scripts, rather than allowing multiple conductors for a cluster, and making users choose one, require that there be only one. I'll send a PR to fix it.
This does not yet include the UI part for multiple logins.
=> Redo data model for authentication to allow for multiple logins

src/data_storage/internals.ts, src/datamodel/database.ts, src/datamodel/ui.ts, src/gui/components/record/form.tsx
This needs a better UI (currently it's just a text field at the bottom to the page), but the data model is set up.
=> Add simple interface for UGC

src/sync/sync-toggle.ts
I seemed to have forgotten to clean this one when I did the attachment code.
=> Move error level message to helpful debug one

ios/App/App/Info.plist, package-lock.json, package.json
This might be one approach to getting authentication working again on iOS.
=> Add new deps for custom url scheme test

src/index.tsx
This is mainly for debugging how the app gets called from Safari.
=> Add logging of capacitor app state

package.json, serve.json
Unclear what version this was, but explicitly set minifauxton to be ignored.
=> Serve seemed to break minifauxton

package-lock.json, package.json
This is primarily to test whether sharing is better behaved on Android than the current Filesystem setup.
=> Add capacitor share plugin

android/app/capacitor.build.gradle, android/app/src/main/assets/capacitor.plugins.json, android/capacitor.settings.gradle, ios/App/Podfile
=> cap update for browser, device, share

.cspell.json, .faimsWords.txt, android/app/capacitor.build.gradle, android/app/src/main/assets/capacitor.plugins.json, android/capacitor.settings.gradle, ios/App/Podfile, jest.config.ts, package-lock.json, package.json, src/gui/component_registry/bundle_components.ts, src/gui/components/qrcode/DisplayQR.css, src/gui/components/qrcode/DisplayQR.tsx, src/gui/fields/qrcode/QRCodeFormField.module.css, src/gui/fields/qrcode/QRCodeFormField.tsx, src/gui/fields/qrcode/QRCodeFormFieldSettings.tsx, src/gui/fields/qrcode/index.tsx, src/gui/pages/project-settings.tsx, src/jest/__mocks__/@capacitor-community/barcode-scanner.ts
Adds a QRCodeFormField and a DisplayQR component.
=> Add support for QR code scanning and display

src/context/store.tsx, src/datamodel/core.ts, src/sync/connection.ts, src/sync/process-initialization.ts, src/utils/status.tsx
This should mean the sync lights blink.
=> Wire up sync status lights to sync code

src/gui/pages/about-build.tsx, src/utils/downloadShare.ts
This can be removed once we've sorted out the crashes.
=> Add logging around share button for debugging

src/gui/components/record/RecordData.tsx, src/gui/components/record/formButton.tsx
=> Fix issues

src/gui/components/record/RecordData.tsx, src/gui/components/record/formButton.tsx, src/gui/components/record/relationships/RelatedInformation.tsx
Fix FAIMS3-428 Form  Null error
=> Fix FAIMS3-428 Form  Null error

src/sync/new-project.ts
'local_draft', 'awaiting_approval', 'published', 'archived' and 'deleted' are the valid statuses.
=> Set status correctly for new projects

src/gui/components/notebook/index.tsx, src/gui/components/notebook/settings/auto_incrementers.tsx, src/gui/components/notebook/settings/index.tsx, src/gui/components/record/form.tsx, src/gui/fields/BasicAutoIncrementer.tsx
=> Update UI fix

src/gui/components/notebook/index.tsx, src/gui/components/notebook/settings/index.tsx, src/gui/components/notebook/settings/sync_switch.tsx, src/gui/components/record/RecordData.tsx, src/gui/components/record/conflict/conflictDialog.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/conflict/conflictstyle.tsx, src/gui/components/record/form.tsx, src/gui/pages/about-build.tsx, src/gui/pages/record.tsx
Fix: duplicate notebook settings header removed
Fix: adding back the sync-toggle-data per notebook setting
Refactor: about-build UX updated, removing UI testing buttons
Fix: handleChangeTab not being passed down through props properly to conflict dialogue 
FAIMS3-623 FAIMS3-577 FAIMS3-560
=> UI bug fixes 

src/data_storage/index.ts, src/data_storage/merging.ts, src/datamodel/database.ts
Previously relationships were not checked when doing automerge.
See FAIMS3-602 for more details.
=> Consider relationships in automerge

src/utils/downloadShare.ts
Any missing directories will be automatically created if need be now.
=> Add recursion to file system save

src/gui/components/notebook/settings/index.tsx, src/gui/components/notebook/settings/status.tsx, src/gui/components/notebook/settings/sync_switch.tsx, src/gui/components/workspace/notebooks.tsx
allowing the user to quickly disable syncing.
FAIMS3-627
=> Add notebook sync switcher to workspace list of notebooks

src/gui/components/workspace/notebooks.tsx
(only show sync switch if published/archived)
=> add sync conditions to notebook list 

src/context/store.tsx, src/gui/components/alert.tsx, src/gui/components/notebook/settings/index.tsx, src/gui/components/notebook/settings/sync_switch.tsx, src/gui/components/workspace/notebooks.tsx
feat: sync switch ui improvements (waiting for await promise to resolve) feat: show 'working' status whilst waiting for said promise (might be worth rolling this out on other components) refactor: move notebook switch status condition into component itself
FAIMS3-627
=> feat: Mobile view for notebook list

src/utils/downloadShare.ts
Hopefully this will test us which paths work on which system, and allow for further debugging of any errors/crashes.
=> Try all paths when sharing

src/gui/components/notebook/settings/sync_switch.tsx, src/gui/components/workspace/notebooks.tsx, src/gui/pages/about-build.tsx, src/gui/pages/workspace.tsx
feat: parse date strings properly in notebook list
fix: remove status 'undefined' from notebook switch visibility array feat: improve mobile view for notebook list
feat: clean up about-build
FAIMS3-619 FAIMS3-627
=> notebook list updates

src/utils/downloadShare.ts
=> changed test share to dir, instead of external in loop

src/gui/components/record/RecordData.tsx, src/gui/components/record/relationships/index.tsx
=> feat: add links to record review tab

src/gui/components/project/CreateProjectCard.tsx, src/gui/components/project/data/componenentSetting.tsx, src/gui/components/record/branchingLogic.tsx
add both views and fields controller
=> add both views and fields controller

src/gui/pages/about-build.tsx
feat: add dialog to wipe button in case the button is hit by mistake!
=> feat: update about-build for better mobile experience.

src/utils/downloadShare.ts
=> More exploratory testing for share

src/utils/downloadShare.ts
=> better filenames for export identification

src/native_hooks.ts
Hopefully this will allow tracing what's happening as the app urls are sent on different OSes.
=> Add additional logging to clarify app url handling

src/utils/downloadShare.ts
=> Change order again, remove time from date

src/data_storage/index.ts, src/gui/components/notebook/settings/auto_incrementers.tsx, src/gui/components/project/CreateProjectCard.tsx, src/gui/components/project/data/componenentSetting.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/conflict/conflictform.tsx, src/gui/components/record/conflict/conflictpanel.tsx, src/gui/components/record/relationships/create_links/index.tsx, src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/record/relationships/types.tsx, src/gui/components/record/view.tsx, src/gui/fields/FileUploader.tsx, src/gui/fields/RelatedRecordSelector.tsx, src/gui/fields/TakePhoto.tsx, src/gui/fields/selectadvanced.tsx
=> Fix conflict issue

src/data_storage/index.ts, src/gui/components/project/tabs/ProjectBehaviour.tsx, src/gui/components/project/tabs/ProjectOverview.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/conflict/conflictform.tsx, src/gui/components/record/conflict/conflictpanel.tsx, src/gui/components/record/fields.tsx, src/gui/components/record/relationships/RelatedInformation.tsx, src/gui/components/record/relationships/create_links/create_record_link.tsx, src/gui/components/record/relationships/create_links/index.tsx, src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/ui/Dialog.tsx, src/gui/fields/RelatedRecordSelector.tsx, src/gui/pages/record-create.tsx
- Add loading for child/parent record
- Add Form valid checking and isSubmit checking, so add link is not valid when form is not valid or is submit
- Fix attachment 404 error
- Fix Conflict timestamp issue( select right, show left)
- Fix RelatedField value select error ( select right, show left)
=> Fix child parent issue

src/gui/components/metadataRenderer.tsx, src/gui/components/notebook/add_record_by_type.tsx, src/gui/components/notebook/index.tsx, src/gui/components/notebook/record_table.tsx, src/gui/components/notebook/settings/index.tsx, src/gui/components/notebook/table.tsx, src/gui/components/workspace/notebooks.tsx, src/gui/layout/appBar.tsx, src/gui/pages/notebook.tsx, src/gui/pages/record-create.tsx, src/gui/pages/record.tsx, src/gui/pouchHook.ts
This should help trace why the double render occurs, but also reduce the level of irritation of users at the double render.
=> Add lots more logging and new timeouts

src/gui/components/project/data/componenentSetting.tsx, src/gui/fields/selectadvanced.tsx
=> add label for image

src/buildconfig.ts, src/databaseAccess.tsx, src/datamodel/ui.ts, src/gui/components/autoincrement/edit-form.tsx, src/gui/components/footer/supportEmail.tsx, src/gui/components/notebook/settings/activation-switch.tsx, src/gui/components/notebook/settings/auto_incrementers.tsx, src/gui/components/notebook/settings/index.tsx, src/gui/components/notebook/settings/sync_switch.tsx, src/gui/components/workspace/notebooks.tsx, src/gui/fields/BasicAutoIncrementer.tsx, src/gui/layout/appBar.tsx, src/gui/pages/about-build.tsx, src/sync/process-initialization.ts
UI is in place, James to hook up :)
=> Notebook activation switch

src/datamodel/ui.ts, src/gui/components/record/relationships/RelatedInformation.tsx, src/gui/components/record/relationships/create_links/create_record_link.tsx, src/gui/components/record/relationships/create_links/index.tsx, src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/record/relationships/types.tsx, src/gui/fields/RelatedRecordSelector.tsx
=> Add prefer label

src/datamodel/ui.ts, src/gui/components/record/relationships/RelatedInformation.tsx, src/gui/components/record/relationships/create_links/create_record_link.tsx, src/gui/components/record/relationships/create_links/index.tsx, src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/record/relationships/types.tsx, src/gui/fields/RelatedRecordSelector.tsx
Reverts FAIMS/FAIMS3#830. This patch and the previous have caused WSOD. See FAIMS3-650
=> Revert "Add prefer label"

src/datamodel/ui.ts, src/gui/components/record/relationships/RelatedInformation.tsx, src/gui/components/record/relationships/create_links/create_record_link.tsx, src/gui/components/record/relationships/create_links/index.tsx, src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/record/relationships/types.tsx, src/gui/fields/RelatedRecordSelector.tsx
=> Revert "Revert "Add prefer label""

src/buildconfig.ts, src/databaseAccess.tsx, src/datamodel/ui.ts, src/gui/components/autoincrement/edit-form.tsx, src/gui/components/footer/supportEmail.tsx, src/gui/components/notebook/settings/activation-switch.tsx, src/gui/components/notebook/settings/auto_incrementers.tsx, src/gui/components/notebook/settings/index.tsx, src/gui/components/notebook/settings/sync_switch.tsx, src/gui/components/workspace/notebooks.tsx, src/gui/fields/BasicAutoIncrementer.tsx, src/gui/layout/appBar.tsx, src/gui/pages/about-build.tsx, src/gui/pages/notebook.tsx, src/sync/process-initialization.ts
Reverts FAIMS/FAIMS3#833
As per slack
=> Revert "Revert "Notebook activation switch""

src/utils/downloadShare.ts
=> Stop once we have shared without errors

src/utils/downloadShare.ts
This should fix the looping hopefully.
=> Return rather than break in file share button

src/gui/components/autoincrement/edit-form.tsx
Improved UI - updating autoincrementer values shows a success alert. 
=> fix: success alert added for autoincrementer form submit

src/gui/components/autoincrement/edit-form.tsx, src/gui/components/notebook/settings/auto_incrementers.tsx, src/gui/fields/BasicAutoIncrementer.tsx, src/gui/fields/TakePhoto.tsx
This should allow users to change the state of the autoincrementors by adding, removing and deleting ranges as desired, as long as there remains at least one range.
Should fix FAIMS3-665, FAIMS3-643 and FAIMS3-644.
=> Fix some issues related to autoincrementors

src/gui/components/autoincrement/edit-form.tsx
Looks like this was due to a bad merge.
Should resolve https://faimsproject.atlassian.net/browse/FAIMS3-643?focusedCommentId=13700
=> Remove the extra delete range button

src/gui/components/notebook/delete.tsx, src/gui/components/notebook/draft_table.tsx, src/gui/components/notebook/index.tsx, src/gui/components/notebook/record_table.tsx, src/gui/components/notebook/refresh.tsx, src/gui/pages/notebook.tsx, src/utils/useInterval.tsx
Alert will change to warning after ten minutes. Error handling in place. Refresh functionality needs filling in.
FAIMS3-670
=> feat: Adds manual refresh interface to notebook.

src/gui/components/notebook/record_table.tsx
This should mean only when the refresh button is hit will new records appear.
Fixes FAIMS3-670.
=> Remove listening in record tab

src/gui/components/authentication/login_form.tsx
=> See if using popover fixes iOS webview

src/gui/components/authentication/login_form.tsx
Reverts FAIMS/FAIMS3#867
Apparently the keyboard bug went away when the iPad was restarted...
=> Revert "See if using popover fixes iOS webview"

src/data_storage.test.ts, src/data_storage/index.ts, src/datamodel/core.ts, src/datamodel/ui.ts, src/gui/components/record/RecordData.tsx, src/gui/components/record/form.tsx, src/gui/components/record/relationships/RelatedInformation.test.tsx, src/gui/components/record/relationships/RelatedInformation.tsx, src/gui/components/record/relationships/create_links/create_record_link.tsx, src/gui/components/record/relationships/create_links/index.tsx, src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/record/relationships/index.tsx, src/gui/components/record/relationships/record_links.tsx, src/gui/components/record/relationships/types.tsx, src/gui/components/ui/record_link.tsx, src/gui/fields/RelatedRecordSelector.tsx, src/gui/pages/record-create.tsx, src/gui/pages/record.tsx
- Add delete action in Link for deleted record
- [FAIMS3-671] fix breadcrumb for draft
- fix broken link
=> Fix delete relation

src/gui/components/record/relationships/RelatedInformation.tsx, src/gui/components/record/relationships/create_links/create_record_link.tsx, src/gui/pages/record.tsx
=> fix FAIMS3-671

src/data_storage/internals.ts, src/data_storage/merging.ts, src/datamodel/database.ts
=> Merge pouch record documents as part of automerge

src/gui/components/record/form.tsx, src/gui/pages/record.tsx
=> add_check_deleted_record

src/gui/fields/DateTimeNow.tsx
=> add save date to IOS string

src/gui/components/notebook/record_table.tsx, src/gui/components/notebook/table.tsx, src/gui/components/record/conflict/conflictLinkBar.tsx, src/gui/components/record/conflict/conflictdroplist.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/relationships/RelatedInformation.tsx, src/gui/fields/DateTimeNow.tsx, src/gui/fields/LocalDate.tsx, src/gui/fields/TemplatedStringField.tsx, src/gui/pages/record.tsx
=> add convert of timestamp

package-lock.json, package.json, src/gui/pages/about-build.tsx, src/sync/data-dump.ts, src/utils/downloadShare.ts
This tries to stream JSON into a blob on browsers, and to the file system on apps. On browsers this may use large amounts of memory, but absent an easy way to stream to the file system, we don't have many options.
=> Initial attempt for streaming dump

src/sync/data-dump.ts
This should avoid loading too much into memory at once, and hopefully avoid any possible crashes.
=> Redo browser dumping to download many files

src/gui/components/record/meta.tsx, src/gui/components/record/relationships/create_links/index.tsx, src/gui/pages/notebook.tsx, src/gui/pages/record-create.tsx, src/gui/pages/record.tsx
feat: add more descriptive language in meta tab
FAIMS3-232
=> feat: add delete dialog back in for record/draft meta tab

src/gui/components/ui/record_link.tsx
=> change delete icon to chip

src/gui/components/record/conflict/conflictDialog.tsx, src/gui/components/record/conflict/conflictbutton.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/conflict/conflictform.tsx, src/gui/components/record/conflict/conflictpanel.tsx, src/gui/components/record/conflict/conflictstyle.tsx, src/gui/components/record/conflict/conflicttoolbar.tsx, src/gui/components/record/conflict/recordTab.tsx, src/gui/components/record/relationships/record_links.tsx, src/gui/pages/record.tsx
=> feat: UI/UX improvements to conflict resolution tool.

.github/workflows/google-play-build.yml, .github/workflows/human-app-build.yml, .github/workflows/nightly-android-testbuild.yml
=> Add BUGSNAG_KEY to build scripts

capacitor.config.json
I had this stashed, pushing it in case it is useful
=> Enable web debugging on android

ios/App/App/Info.plist
Signed-off-by: james.tocknell@mq.edu.au
=> Allow files to appear in the iOS file app

ios/App/App/Info.plist
This reverts commit bfbee4030360c062a7b43201e4d2225c393e4f20.
=> Revert "Allow files to appear in the iOS file app"

src/sync/data-dump.ts, src/utils/downloadShare.ts
It seems to have broken for some reason, this should be re-examined in some future development phase.
=> Revert streaming on mobile

package.json, src/gui/components/ui/breadcrumbs.test.tsx, src/gui/components/ui/inProgress.test.tsx, src/gui/pages/404.test.tsx, src/gui/pages/about-build.test.tsx, src/gui/pages/index.test.tsx, src/gui/pages/notebook.test.tsx, src/gui/pages/notebook.tsx, src/gui/pages/workspace.test.tsx
- Add coverage for index, breadcrumbs, notebook, inprogress components
- Add --detectOpenHandles to coverage script
=> Add tests for index, breadcrumbs, notebook, inprogress components

src/gui/pages/project-create.test.tsx, src/gui/pages/record-create.test.tsx
Add tests for project-create and record-create
=> Add tests for project-create and record-create

src/App.css, src/gui/theme/index.tsx
Minor updates to design colours.
=> Design update

package-lock.json, package.json, src/buildconfig.ts, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/fields.tsx, src/gui/components/record/form.tsx, src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/record/relationships/record_links.tsx, src/gui/components/ui/record_link.test.tsx, src/gui/components/workspace/notebooks.tsx, src/gui/pages/record.tsx, src/gui/pouchHook.ts, src/sync/connection.ts, src/sync/draft-state.ts, src/sync/process-initialization.ts, src/sync/sync-toggle.ts, src/utils/helpers.tsx
Problem with view initialisation that prevented it finding out what the viewname and viewset are for the record.
=> Fix bug that prevents the record edit view showing

package-lock.json, package.json, src/gui/component_registry/bundle_components.ts, src/gui/fields/RandomStyle.tsx, src/gui/fields/RichText.test.tsx, src/gui/fields/RichText.tsx, src/gui/fields/maps/MapFormField.test.tsx, src/gui/fields/utils.tsx, src/projectMetadata.test.ts, src/projectMetadata.ts
Implement a Markdown based Rich Text Field to replace RandomStyle which is a security attack vector as it allows injection of arbitrary HTML into the form.  
We will deprecate RandomStyle and remove it in a later version once all notebooks have been updated.
=> Rich text field

src/gui/components/record/Annotation.tsx, src/gui/components/record/conflict/conflictfield.tsx, src/gui/components/record/form.test.tsx, src/gui/components/record/form.tsx, src/gui/components/record/view.tsx, src/gui/fields/FileUploader.tsx, src/gui/fields/RelatedRecordSelector.tsx, src/gui/fields/RichText.test.tsx, src/gui/fields/TakePhoto.tsx, src/gui/fields/TemplatedStringField.tsx, src/gui/fields/checkbox.tsx, src/gui/fields/maps/MapFormField.test.tsx, src/gui/fields/radio.tsx, src/gui/fields/select.tsx, src/gui/fields/selectadvanced.tsx, src/gui/fields/utils.tsx
Fixing up some issues with the notebook format FAIMS-716.
=> Improvements to notebook json format

.licenserc.json, package-lock.json, package.json, src/conditionals.test.ts, src/conditionals.ts, src/gui/components/record/branchingLogic.test.tsx, src/gui/components/record/branchingLogic.tsx, src/gui/components/record/form.test.tsx, src/gui/components/record/form.tsx, src/uiSpecification.ts
Rewrite of branching logic to add more general conditional expressions.
=> Update branching logic

src/gui/components/record/fieldPersistentSetting.tsx
=> treat persistent field as boolean

src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/record/relationships/record_links.tsx
List of relations always shows 1-5 of 5 in pagination control
=> Fix bug in pagination of DataGrid in relation field

src/gui/components/record/relationships/RelatedInformation.tsx, src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/record/relationships/record_links.tsx, src/gui/fields/RelatedRecordSelector.tsx
=> Fix-related-record-init-bug

infrastructure/aws-cdk/README.md, infrastructure/aws-cdk/configs/sample.json, infrastructure/aws-cdk/fetch-config.sh, infrastructure/aws-cdk/lib/components/conductor.ts, infrastructure/aws-cdk/lib/components/couch-db.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts, infrastructure/aws-cdk/package.json, infrastructure/aws-cdk/push-config.sh, infrastructure/aws-cdk/validateConfig.ts
Implements auto scaling for ECS based on memory and CPU thresholds. Adds this to configuration and documents. 
Adds instance sizes, ECS task memory/cpu, domain names, and app URLs to config object and updates appropriate documentation. 
Adds fetch/push config scripts, and corresponding `package.json` entries, to pull and push environment specific configs from a private configuration repo. This automates the process of copying and potentially overwriting files from private configuration repo. Usage is documented in README.md.
Adds a `validate-config` script to the `package.json` which validates the targeted environment's configuration against the Zod schema.
=> feat: improved configuration and ECS auto scaling

.github/actions/config/action.yml, .github/workflow-templates/cdk-deploy.yml, .github/workflows/deploy-aws-cdk.yml, app/package.json, infrastructure/aws-cdk/config.sh, infrastructure/aws-cdk/lib/components/front-end.ts, package-lock.json, package.json
Implements a template github actions workflow for deploying the CDK application using the specialised organisation config.
The intention is for this not to be recognised as a legitimate workflow, and instead used as a basis for organisation + environment specific deployments e.g. for the BSS.
=> feat: Github Actions workflow for CDK operations

app/src/App.tsx
[BSS-301](https://jira.csiro.au/browse/BSS-301)
App shows blank 404 page when there is an issue.
- removed 404 component route (this component is redundant as it has no path)
- added default route that redirects home
- log into app (if necessary) and navigate to a notebook (survey)
- refresh the page and verify that it navigates home
- (optional) type garbage into the url (e.g. http://localhost:5000/abc123) and verify it navigates home
This does not address the underlying issue but improves the user experience if something were to go wrong in production.
=> fix: default route redirect

app/src/gui/components/ui/inProgress.tsx
Parent Jira Issue: browse
Subtask: https://jira.csiro.au/browse/BSS-299
Minor enhancement to inprogress component to make it more clearly visible to the developer.
- Typography updated
- More clearly visible
- When in local dev mode, you should be able to see "feature in progress" disclaimer with icon at the bottom of the content of the page.
- [Y] I have confirmed all commits have been signed.
- [Y] I have added JSDoc style comments to any new functions or classes.
- [Y] Relevant documentation such as READMEs, guides, and class comments are updated.
=> minor enhancements to inProgress component

.github/workflows/publish-conductor.yml, api/package.json, bundle.sh, package-lock.json
Adds a copy step to the tsc build which bundles the views into the output, reducing fragility of build by moving this logic out of additional scripts into the relevant build script.
Adds the following files
- views
- public (and public/images)
Confirming that public static content is being hosted properly i.e. 
The way to validate the `views` location is to run the docker image in a shell entry point and have a look at the files. The views files should be in `/app/api/build/src/views` as indicated by the below current error message: 
```
Error: Failed to lookup view "auth" in views directory "/app/api/build/src/views"
at Function.render (/app/node_modules/express/lib/application.js:597:17)
at ServerResponse.render (/app/node_modules/express/lib/response.js:1048:7)
at _clear …
```
=> build: fixing missing views in conductor docker image

.github/workflows/nightly-android-testbuild.yml, app/.env.dist, app/.github/workflows/appstore-deploy.yml, app/.github/workflows/appstore-testflight.yml, app/.github/workflows/fieldmark-google-play-prod.yml, app/src/gui/components/footer/footerEHTML.tsx, app/src/gui/components/footer/index.tsx, app/src/gui/components/footer/supportEmail.tsx, app/src/gui/components/record/form.tsx, app/src/gui/components/record/formButton.tsx, infrastructure/aws-cdk/lib/components/front-end.ts
Removing dev tools, removing all mentions of VITE_SERVER, removing VITE_SERVICES.
=> chore: remove dev tools

infrastructure/aws-cdk/README.md, infrastructure/aws-cdk/configs/sample.json, infrastructure/aws-cdk/lib/components/conductor.ts, infrastructure/aws-cdk/lib/components/front-end.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts
Adding uiConfiguration to JSON configuration and exposing in environment variables to front end, removing google auth options.
=> build: aws deployment configuration updates

docs/developer/Configuration.md
Adds `docs/Configuration.md` which describes the forms of configuration in the FAIMS3 application, and a process to determine where configuration should occur.
=> docs: configuration architecture and approach

app/src/gui/components/workspace/notebooks.tsx
](https://jira.csiro.au/browse/BSS-430)
Renaming Start syncing to Start using based on feedback from Elana.
- Rename start syncing survey to start using survey
- To be confirmed change is to move this section below Create New Survey button
- To be confirmed Align the language for BSS where it says , go to Available survey section to Active/Not Active
View these changes on List of surveys page
- [y ] I have added JSDoc style comments to any new functions or classes.
- [y ] Relevant documentation such as READMEs, guides, and class comments are updated.
=> renaming to start syncing to using.

app/src/gui/components/workspace/notebooks.tsx
https://jira.csiro.au/browse/BSS-434
Remove  "status" column which shows Notebook/survey published as discussed
Explain how to test the changes.
List of notebooks/surveys page shouldn't show status column which has "published status" displayed.
Add any additional information or context about the pull request here.
- [y ] I have added JSDoc style comments to any new functions or classes.
- [y ] Relevant documentation such as READMEs, guides, and class comments are updated.
=> Remove status column which has published as discussed.

app/src/gui/components/notebook/settings/activation-switch.tsx, package-lock.json
Refining activation details and removing mention of non existent deactivate feature. 
- removes mention of deactivate since this does not exist
- simplifies wording and removes unnecessary dot points
- adds recommendation to activate while offline with stable connection
- uses the configured notebook name instead of hardcoded "survey"
=> feat: improving activate wording

app/src/gui/components/notebook/add_record_by_type.tsx
Changing button label to 'Add new' instead of 'New'
https://jira.csiro.au/browse/BSS-471
=> chore: changing button label to 'Add new' instead of 'New'

api/views/notebook-landing.handlebars, api/views/register.handlebars
[BSS-470](https://jira.csiro.com/browse/BSS-470)
Add a hint to the required password length on the registration form.
Hint text added, also added autocomplete attributes so browser can pre-fill name and email. 
Also a quick fix for the developer tool to generate random records which broke when Peter started checking types.
Register for a notebook.
=> Add password hint on registration

app/.env.dist, app/src/buildconfig.ts, app/src/gui/components/app-bar/app-bar-heading.tsx, infrastructure/aws-cdk/configs/sample.json, infrastructure/aws-cdk/lib/components/conductor.ts, infrastructure/aws-cdk/lib/components/front-end.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts
Adding heading configuration, adding conductor configs to make server info display more user friendly, exposing through JSON config.
These changes have been deployed to NBIC BSS website.
=> chore: build configuration refinements for CDK workflow

app/src/gui/components/notebook/add_record_by_type.tsx
Adds plus icon to the new site button, same as other new survey button, and removes hardcoded colour.
=> ui: styling on button to add plus icon and non-hardcoded colour

app/src/gui/components/record/form.tsx, app/src/gui/components/record/formButton.tsx
[BSS-459](https://jira.csiro.au/browse/BSS-459)
Removed next and prev buttons for inline layout.
- Removed next and prev buttons for inline layout
1. Upload a survey which uses the inline layout
2. Ensure the buttons have been removed
3. Also test that the buttons appear in tab layout
=> fix: inline buttons

app/src/gui/components/notebook/NewNotebookForListing.tsx
(https://jira.csiro.au/browse/BSS-468)
Updated wording changes from Instantiate to Create new survey (config)
Theming updates to this component 
Please test for both the themes - 'default' and 'bssTheme' to check for the correct theming colors being applied to this section
Create New survey button from list of surveys
Choose template
The disabled and enabled button icon, text and background should align with respective themes.
The dialog title should be Create new survey instead of Instantiate survey
The dialog theme should be according to respective themes.
- [y ] I have added JSDoc style comments to any new functions or classes.
- [ y] Relevant documentation such as READMEs, guides, and class comments are updated.
=> Wording changes create new survey

app/src/gui/components/notebook/datagrid_toolbar.tsx, app/src/gui/components/notebook/index.tsx, app/src/gui/components/workspace/CreateNewSurvey.tsx, app/src/gui/pages/notebook.tsx
https://jira.csiro.au/browse/BSS-461
General improvements in layout, theme.
Review based on changes added in Survey Details, Site details screens.
- [ y] I have added JSDoc style comments to any new functions or classes.
- [ y] Relevant documentation such as READMEs, guides, and class comments are updated.
=> General app improvements based on review

api/src/auth_routes.ts, api/src/index.ts
None
Federated login wasn't returning the token to the app
Login to the app with Google.
=> Fix Federated Login Redirect

app/src/gui/fields/multiselect.tsx, app/src/gui/fields/select.tsx
See Miro!
Multiselect was a bit confusing, add checkboxes to the select to emphasise that more than one can be checked. 
Updates MultiSelect to add checkboxes.
Updates Select to match the new MultiSelect implementation.
View the BSS survey, Hazards should show as the new multiselect with checkboxes.
=> Improve-multiselect

app/src/gui/fields/TakePoint.tsx, app/src/gui/fields/maps/MapFormField.tsx, app/src/gui/fields/maps/MapWrapper.tsx
[BSS-484](https://jira.csiro.com/browse/BSS-484)
Try to do a better job of checking for location permission and informing the
user what to do if it isn't given.
Adds a platform specific error message when location permission isn't 
granted.
Turn of location permission for the page/app and open a notebook that has 
a map location.
=> Better Location Permissions Handling

app/src/gui/components/workspace/notebooks.tsx
Adds a notification for success/failure on refresh button for notebook list.
=> feat: refresh alert on survey refresh

app/src/gui/fields/TakePhoto.tsx
None
TakePhoto wasn't working following a recent change. 
Revert the callback to use an async/await.
Take a photo!
=> revert change to takephoto callback

.github/workflows/nightly-android-testbuild.yml, app/src/gui/components/workspace/notebooks.tsx
None
Adds options to configure THEME and NOTEBOOK_NAME for android build.
Fixes bug in notebook list that gets stuck on one tab.
=> More config options for Android ++

app/src/gui/fields/TakePhoto.tsx, app/src/gui/fields/qrcode/QRCodeFormField.tsx
None
Android app was not asking for permission to use the camera. 
Add an explicit check for camera permission and more useful alerts if it is not available that include instructions on how to grant permission.
Requires Android build, try turning off camera permission.
Add any additional information or context about the pull request here.
=> Improve Camera Permissions on Android

infrastructure/digital-ocean/couchdb/couchdb.tf, infrastructure/digital-ocean/example/README.md, infrastructure/digital-ocean/example/deploy.tf
None
Minor fix to the allocation of domain names for the couchdb
nodes.
=> Digital Ocean Terraform - fix CouchDB domains

app/src/gui/components/notebook/index.tsx, infrastructure/digital-ocean/conductor/conductor.sh, infrastructure/digital-ocean/conductor/conductor.tf, infrastructure/digital-ocean/conductor/variables.tf, infrastructure/digital-ocean/couchdb/couchdb.tf, infrastructure/digital-ocean/couchdb/loadbalancer.tf, infrastructure/digital-ocean/couchdb/variables.tf, infrastructure/digital-ocean/example/deploy.tf
None (Fieldmark)
Some minor updates to the DO configuration to correct
some bugs and add a few more configuration options.
=> Digital Ocean deploy tweaks

api/package.json, app/package.json, designer/package.json
None
Increment and synchronise version numbers in app/api/designer
=> Set all version numbers to 1.0.0

app/src/gui/components/record/formButton.tsx
None
We had one button with 'Save' and one with 'Publish'.
Use 'Publish' in both buttons and restore the note that explains what publish means.
View a form and see the consistent buttons.
=> Make button labels consistent in form

app/ios/App/App/Info.plist, app/ios/App/Podfile.lock, package-lock.json
None
App store review has requested more detail in the permissions text for camera 
permissions in the app.   This PR updates that text and a couple of the other
permissions descriptions.
=> Fix IOS permissions text for camera

app/src/gui/components/notebook/index.tsx, app/src/gui/components/notebook/record_table.tsx
[BSS-530
](https://jira.csiro.au/browse/BSS-530)
Updated  - All Responses" and "My Responses" Tabs (Previously "All Sites" and "My Sites"):
- Make sure to update the JSON configuration to change "Sites" to "Response" for the label update.
- "All Responses" Tab:
Verify that it displays all available records, regardless of who created them.
"My Responses" Tab: Shows only the records created by the currently logged-in user.
This functionality is controlled using the filterByUser flag, which filters data based on the active user.
All Responses" and "My Responses" Tabs:
"All Responses" Tab:
Verify that it displays all available records, regardless of who created them.
"My Responses" Tab:
Log in as a specific user.
Ensure that this tab only shows the records created by the logged-in user. …
=> Update sites to responses and functionality improvements

designer/src/components/design-panel.tsx, designer/src/components/form-editor.tsx, designer/src/components/section-editor.tsx, designer/src/state/uiSpec-reducer.ts, package-lock.json
[BSS-647](https://jira.csiro.au/browse/BSS-647)
This pull request implements the ability to move a section from one form to another within the designer. A dialog box is introduced to let users select the target form, and the section is updated in the state and UI accordingly.
- **State Management:**  
- Implemented the `sectionMovedToForm` action in the Redux reducer to update the state.  
- Removes the section from the source form and adds it to the target form.     
- **User Interaction:**  
- Added a dialog in the `SectionEditor` component to allow users to select the target form.  
- Used radio buttons for form selection to provide a clear and simple UI.  
- Filtered out the `sourceViewSetId` from the `viewSets` object before rendering radio buttons to prevent selecting the same form. …
=> Feat: Move a Section between Forms in Designer

app/bin/prebuildConfig.sh, infrastructure/aws-cdk/lib/components/front-end.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts
Missing double quotes around export causing truncated environment variables. 
Missing environment variables. 
Small fry...
=> fix: various misc build fixes CDK

infrastructure/aws-cdk/README.md, infrastructure/aws-cdk/configs/sample.json, infrastructure/aws-cdk/lib/components/couch-db.ts, infrastructure/aws-cdk/lib/components/front-end.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts, package-lock.json, package.json
Basic deployment CDK script for web.*. New conductor. 
Doesn't work currently due to outdated conductor missing the /users/current route.
=> feat: conductor cdk deploy

api/src/auth_routes.ts, api/src/core.ts, api/views/auth.handlebars, api/views/register.handlebars
Only show OR in the refreshed templates when providers and local is activated.
=> fix: unwanted OR

app/src/gui/components/notebook/delete.tsx, app/src/gui/components/notebook/index.tsx, library/data-model/src/data_storage/index.ts
Fixes async shenanigans + cleans up ui spec waffle.
=> fix: deletion not working

app/src/gui/fields/TakePhoto.tsx
Adds a delete confirmation to removing images.
=> feat: photo deletion confirmation

app/src/gui/components/ui/PermissionAlerts.tsx, app/src/gui/fields/TakePhoto.tsx, app/src/gui/fields/TakePoint.tsx, app/src/gui/fields/maps/MapFormField.tsx, app/src/gui/fields/maps/MapWrapper.css, app/src/gui/fields/maps/MapWrapper.tsx, app/src/gui/fields/qrcode/QRCodeFormField.tsx, app/src/gui/themes/bssTheme/index.tsx, app/src/gui/themes/bubble/index.tsx, app/src/gui/themes/default/index.tsx, app/src/gui/themes/themes.d.ts
- Made location field to incorporate fieldwrapper for consistent styling and formatting with rest of the form fields
-Improved button styling for better visibility & responsiveness
-Added, Larger map icon with proper spacing from the text
-Added hover effects & transition animations for better UX
- Animated checkmark appears when a location is successfully selected
- Dynamic color changes when a selection is missing (red cross feedback)
- Adjusted spacing & text formatting for better clarity
- Responsiveness added
Updated fucntionality:
- If user click save, lat long will be saved and displayed
- If map selection is cleared, the lat long will be updated with alert that its been cleared
- If map point was selected , user clickmap again but close it, nothing gets updated for lat/long, user …
=> Location field made more visually appealing, enahnced ui-ux

api/src/api/notebooks.ts, api/src/couchdb/notebooks.ts, api/src/utils.ts, api/test/backup.test.ts, api/test/utils.ts
[BSS-441](https://jira.csiro.com/browse/BSS-441)
[BSS-632](https://jira.csiro.com/browse/BSS-632)
Exporting CSV files where there is a map form field that is empty didn't have enough commas to line up the columns. 
Also fixed up finding the HRID of a record when exporting (used to name photo files) according to the new HRID code.  
Add photo filenames to the JSON record export.
Create a record in BSS without entering a map location and another with a location.  From Conductor, export CSV and note that there are three empty columns for the missing location and that all subsequent fields line up properly.
Add photos to your records and note the photo filenames in the CSV and corresponding ZIP download contain the proper HRID of the record. 
Get the JSON export at …
=> Fix-csv-json-export

infrastructure/aws-cdk/lib/components/front-end.ts
See change - default debugging settings.
=> build: debugging config CDK

app/src/gui/components/record/fields.tsx, app/src/gui/components/record/form.tsx, app/src/gui/fields/maps/MapFormField.tsx
None
Some 'special' fields were being added to revisions for unknown reasons.
Don't add them.
Make records and observe the lack of extra fields.
=> Remove pointless fields in revisions

app/src/gui/components/notebook/overview_map.tsx, app/src/gui/fields/maps/MapFormField.tsx
[BSS-526](https://jira.csiro.com/browse/BSS-526)
Previously we didn't ask for high accuracy GPS coordinates in the Map form field.
We ask, nicely, for high accuracy.
Hard to test but should result in higher accuracy GPS values.
=> Ask for high accuracy when we get GPS position

app/src/gui/fields/maps/MapFormField.tsx
[BSS-747](https://jira.csiro.com/browse/BSS-747)
When offline, the map field doesn't work. As an interim measure until we have offline maps, show a button to take the current position instead. 
Adds a button to record the current position instead of the usual map control if we're offline.
Load a notebook with a map control, go offline (via the dev tools network tab) and observe the map button changing.   Click to record current location.  Go online again and note that the point recorded is correct.
=> Offline maps position fallback

app/src/gui/components/record/recordStepper.tsx, designer/src/components/field-editor.tsx, designer/src/components/field-list.tsx, designer/src/components/form-editor.tsx, designer/src/components/section-editor.tsx, designer/src/state/uiSpec-reducer.ts
[BSS-748
](https://jira.csiro.au/browse/BSS-748)
Remove shakestepper change for now, will find another way to be able to test it easily 
- [y ] I have added JSDoc style comments to any new functions or classes.
- [y ] Relevant documentation such as READMEs, guides, and class comments are updated.
=> remove shakestepper atm, add later tba to test fully

app/src/gui/components/ui/heading-grid.tsx, app/src/gui/components/ui/tab-grid.tsx, app/src/gui/components/workspace/notebooks.tsx
Quick fix for broken row heights - no need for review on this superficial change related to #1325
=> fix: row heights

app/src/gui/components/record/form.tsx, app/src/gui/components/record/view.tsx, app/src/gui/fields/NumberField.tsx, designer/src/components/Fields/TextFieldEditor.tsx, designer/src/fields.tsx, designer/src/state/initial.ts
[BSS-769 
](https://jira.csiro.au/browse/BSS-769)
- Enhanced Number Field Behavior:
- Users can now optionally set a default numerical value in Designer. 
- If no default value is set, the field remains empty instead of defaulTting to 0.
- If an invalid number is entered, an error "Error with numerical input, please enter a valid number" is shown.
-  enhanced validation & error handling improvements:
- Error messages are cleaned up to avoid redundant helper text.
- [ Y ] I have confirmed all commits have been signed.
- [ Y ]  I have added JSDoc style comments to any new functions or classes.
- [ Y ] Relevant documentation such as READMEs, guides, and class comments are updated.
=> feat: improve number field

app/src/context/projects-context.tsx
[<JIRA_TICKET>](https://jira.csiro.com/browse/<JIRA_TICKET>)
Briefly describe the purpose of this pull request.
List the changes made in this PR.
Explain how to test the changes.
Add any additional information or context about the pull request here.
=> fix: set difference bug on older safari versions 🐛

app/ios/App/App/Info.plist, app/src/gui/components/notebook/add_record_by_type.tsx, app/src/gui/components/notebook/index.tsx, app/src/utils/customHooks.tsx, library/data-model/src/data_storage/internals.ts, library/data-model/src/data_storage/queries.ts, package-lock.json, web/src/components/dialogs/create-project-dialog.tsx, web/src/routes/_protected/projects/index.tsx
=> fix: package lock 🔒

app/ios/App/App/Info.plist, app/src/gui/components/record/form.tsx, package-lock.json, web/package.json, web/src/components/breadcrumbs.tsx, web/src/components/ui/sonner.tsx, web/src/main.tsx, web/src/routes/_protected/profile.tsx
[BSS-838](https://jira.csiro.au/browse/BSS-838)
Added functionality in new conductor to be able to copy the bearer token to clipboard (to match the current functionality in old conductor).
- added bearer token copy button with toast
- cleaned up profile page
- fixed bug with breadcrumbs on non-projects/templates pages
1. Log in to the `/web` platform
2. Click your profile image on the bottom left of the screen (in the sidebar)
3. Click profile
4. Test the copy bearer token button
=> feat: copy bearer token 🧸

app/src/gui/fields/checkbox.tsx, app/src/gui/fields/multiselect.tsx
[BSS-842
](https://jira.csiro.au/browse/BSS-842)
Improved checkbox and label alignment to ensure consistent horizontal alignment across options. 
This fix enhances visual consistency and accessibility by aligning the checkbox icon and label text correctly.
-Navigate to a survey which has checkbox selection user input.
- There are lots of surveys using checkbox for example : Restructured Rapid Sruvey
There's a "fire suppression" section where if you choose "yes" it will conditionally show checkboxes option below
See screenshot below for reference:
-Verify that each checkbox is visibly aligned horizontally with its label text.
-Long labels / multi-line text are wrapping correctly without shifting checkbox alignment.
- Test n desktop view and mobile view.
Let me know incase of any queries. …
=> checkbox alignment fixes

app/src/gui/components/record/form.tsx, web/src/index.css
[BSS-836](https://jira.csiro.au/browse/BSS-836)
Updated the destructive color in dark theme to be more visible (used in warnings and error messages)
- updated the destructive color in dark theme
- yurn on dark mode in the upper right corner of the screen
- navigate to a destructive template/project action (such as update/archive)
- verify red is more visible
=> fix: darkmode red 🚗

app/ios/App/Matchfile
None
This Matchfile is not used but is blocking the build of BSS (I think).
=> Remove unused matchfile

app/src/gui/components/notebook/draft_table.tsx, app/src/gui/components/notebook/record_table.tsx, app/src/utils/useDataGridStyles.tsx, app/src/utils/useScreenSize.tsx
[BSS-788
](https://jira.csiro.au/browse/BSS-788
)## Description
**THIS PR IS COPY OF THIS APPROVED & REVIEWED PR, due to major conflict with main this new PR has been created which is synced with latest main.** Old PR for reference:  https://github.com/FAIMS/FAIMS3/pull/1410
Briefly describe the purpose of this pull request.
This PR significantly improves the Drafts Table component by:
- Cleaning up the component structure and code
- Making the UI more user-friendly and visually consistent with the "My Sites" → Records table
- Adding and renaming relevant columns for better readability
- Enhancing the mobile experience to match the stacked layout of the Records table on smaller screens
- Clear documentation (docstrings) for functions and logic within the file
Major Improvements
- Field ID …
=> Drats enhancements copy pr

web/src/components/forms/create-project-form.tsx
Fixes https://jira.csiro.au/browse/BSS-890 Just very simple missing param
=> fix: creating project in team

web/src/components/dialogs/remove-user-from-project-dialog.tsx, web/src/components/tables/project-users.tsx, web/src/components/tabs/project/users.tsx, web/src/hooks/queries.ts
Fixes
https://jira.csiro.au/browse/BSS-892
The issue was a) using the /api/users endpoint instead of /api/notebooks/<id>/users b) not typing the response so the data was :any all the way down.
=> fix: project users clean up

web/src/components/dialogs/data-export-dialog.tsx, web/src/components/dialogs/photo-export-dialog.tsx, web/src/components/dialogs/project-from-template.tsx, web/src/components/forms/create-project-form.tsx, web/src/components/tables/project-invites.tsx, web/src/components/tables/projects.tsx, web/src/components/tables/templates.tsx, web/src/routes/_protected/projects/$projectId.tsx, web/src/routes/_protected/projects/index.tsx, web/src/routes/_protected/teams/$teamId.tsx
bunch of hardcodes - and improving tab typing to allow different labels to enum tabs
=> fix: hardcoded project name

Dockerfile, package-lock.json
Fixes local dev script due to unnecessary package lock (I believe monorepo parent lock includes this now).
=> fix: removing package lock copy

designer/src/components/field-editor.tsx
one liner - config got dropped at some point
=> fix: missing configuration for exclusive fields

.github/workflows/appstore-deploy.yml, .github/workflows/appstore-testflight.yml, .github/workflows/fieldmark-google-play-prod.yml, .github/workflows/nightly-android-testbuild.yml, docs/developer/docs/source/markdown/Android-Deployment.md, docs/developer/docs/source/markdown/IOS-Deployment.md
[BSS-926](https://jira.csiro.com/browse/BSS-926)
Updates the configuration for mobile app build workflows to match recent changes.
Will require additional variables and secrets to be set on GitHub.
=> Add new config variables to workflow builds

app/index.html, app/src/App.css
None
Adds some space at the top of the screen based on device variables (IOS) or a fixed size (Android) to 
allow space for the camera notch.
=> Make space for the notch in some mobile devices

api/package.json, app/package.json, designer/package.json, library/data-model/package.json, package.json, web/package.json
=> Bump all package versions to 1.2.0

web/.env.dist, web/index.html, web/src/constants.ts, web/src/main.tsx
Changes default to Control Centre instead of center and makes this an optional env variable.
=> feat: web configurable website title

.github/workflows/appstore-deploy.yml, app/bin/prebuildIOS.sh
None
Minor updates to IOS configuration:
- set the App Name in info.plist, don't hard code as Fieldmark
- tweak the GitHub workflows so that production matches testing more closely
=> IOS Deployment Fixes

app/android/app/capacitor.build.gradle, app/android/app/src/main/assets/capacitor.plugins.json, app/android/capacitor.settings.gradle, app/capacitor.config.dist.json, app/ios/App/App/AppDelegate.swift, app/ios/App/App/Info.plist.dist, app/ios/App/Podfile, app/ios/App/Podfile.lock, app/package.json, app/src/App.css, app/src/App.tsx, package-lock.json
[BSS-920](https://jira.csiro.com/browse/BSS-920)
The status bar at the top of screen was being overlapped on Android and was not visible on IOS. 
Introduced the @capacitor/status-bar plugin to enable inserting the proper spacing on both platforms.
Also changed the IOS configuration which was hiding the status bar. Now showing and we leave space
for it as necessary.
IOS:
Android:
Test on IOS and Android builds of the app.
=> Fix IOS/Android status bar visibility

docs/developer/docs/source/markdown/Android-Deployment.md
[BSS-1006
](https://jira.csiro.au/browse/BSS-1006
[BSS-995
](https://jira.csiro.au/browse/BSS-995)
)
Updated Android App Setup and Deployment documentation in markdown.
=> updated detailed android app setup and deployment documentation in md

app/src/buildconfig.ts
=> fix: VITE_MIGRATE_OLD_DATABASES undefined

api/src/auth/authRoutes.ts, api/src/couchdb/notebooks.ts, api/test/couchdb.test.ts, app/src/gui/components/record/conflict/conflictform.tsx, app/src/gui/components/record/relationships/RelatedInformation.tsx, app/src/gui/components/record/relationships/field_level_links/datagrid.tsx, app/src/gui/fields/maps/MapWrapper.tsx, package-lock.json, web/src/components/forms/export-project-form.tsx, web/src/designer/components/Fields/BaseFieldEditor.tsx, web/src/designer/components/Fields/BasicAutoIncrementer.tsx, web/src/routes/_protected.tsx
None
Build is failing due to stale pacakge-lock.json
Update pacakge-lock.json and fix a few lint warnings due to extra imports and whitespace.
The build should work.
=> Fix Stale package-lock.json

app/src/gui/pages/about-build.tsx
None
Trying to debug the ongoing pouchdb sync problem. This adds a checkbox to toggle debugging output
to the console so we can gather information from stuck browsers (devices will be harder...)
=> Add checkbox to toggle pouchdb debug in about-build page

.github/workflows/appstore-deploy.yml, .github/workflows/appstore-testflight.yml
None
IOS build is not working
Update version of XCode used in the build. Problem was that the target IOS version was not supported. Must be a change in defaults somewhere that triggered this.
=> Fix IOS Build in CI

app/src/context/slices/helpers/databaseService.ts, app/src/context/slices/projectSlice.ts, app/src/gui/components/record/form.tsx, app/src/gui/pages/about-build.tsx, library/data-model/src/data_storage/internals.ts
#1632 
We are seeing an error on IOS devices (via BugSnag) where the database connection seems to disappear leading to errors reading and writing to the database. 
I can't reproduce this error.  It may be related to a bug in Webkit (https://bugs.webkit.org/show_bug.cgi?id=282093).
This PR adds a new operation validateLocalDatabases to the databaseService which looks at each local database connection and re-creates it if it is broken (by a db.info() check).   We add a button in About Build that invokes this operation.  
I have done some testing with a 'damage' function that intentionally closes the databases - this can be enabled in about-build.tsx.   
We won't know if this works until a user has this problem again and is able to try this remedy.
Logging is enabled via BugSnag so we should …
=> Mitigating the database connection failure

infrastructure/aws-cdk/configs/sample.json, infrastructure/aws-cdk/lib/components/front-end.ts, infrastructure/aws-cdk/lib/config.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts
Exposes bugsnag key to vite build for app in CDK infra.
=> feat: bugsnag CDK

app/bin/bugsnag-sourcemaps.sh
[<JIRA_TICKET>](https://jira.csiro.com/browse/<JIRA_TICKET>)
allow overwrite of existing sourcemaps to fix CI 409)
=> add flag for overwrite
