FAIMS/FAIMS3

src/sync/index.ts
Fixes switching sync on/off disabling data pushing to couch and removing event listeners.
We might need to wait for pushing to work so that this can be tested (Hence WIP)
This commit fixes that by adding a SyncHandler, and pull/push options,
to LocalDBRemote data, and moving out the ensure_synced_db logic to
setLocalConnection, so it can also be used by the sync toggle.
This means that the initial db sync and further syncs all use the same
logic to set pull/push options and setup event emitters.
Also added is a thing that got caught due to these changes: SyncHandler
didn't have a way to cancel its timeouts when the DB it was listening to
is destroyed.
=> Fixes to sync toggling

src/gui/components/observation/table.tsx
There is a planned change in how we're going to store the data to handle
the ACLs and work with revisions in a more user-friendly way, but we're
holding that off to beta. That will make managing the creation
information easier (so we don't need to try to keep track of it via the
form), so we're going to hide the dummy data for now.
=> Hide creation information for now

src/gui/components/observation/table.tsx
This was caused by using the 'rows' state variable, but not having it
in the dependencies of useEffect makes it possible for rows to be out
of date.
=> Fix issue of observation list sometimes not updating

src/gui/components/observation/form.tsx
This was caused by the `||` operator taking 0 to be falsey,
so it used a number from the form's defaults or existing data instead
of using what's in the field
=> Fix the number zero not being settable in forms.

src/data_storage.test.ts, src/data_storage/index.ts, src/databaseAccess.tsx, src/datamodel.ts, src/dummyData.ts, src/gui/components/observation/delete.tsx, src/gui/components/observation/form.tsx, src/gui/components/observation/meta.tsx, src/gui/pages/observation-create.tsx, src/gui/pages/observation.tsx, src/sync/databases.ts, src/sync/events.ts, src/sync/index.ts, src/sync/process-initialization.ts, src/sync/state.ts, src/sync/stateful-event-handling.ts, src/sync/sync-toggle.ts
This refactors the type for the datadb and moves the data_storage to its own directory. One last change that we may want to make is to move some of the databaseAccess code into data_storage (e.g. the listeners)? @aidanfar0 Is there anything that could cause issues with?
=> Data model prep

.eslintrc.json, src/data_storage/index.ts, src/data_storage/internals.ts, src/data_storage/merging.test.ts, src/data_storage/merging.ts, src/datamodel/database.ts, src/sync/state.ts
This currently adds the logic for basic automerging.
I've set this as draft as I need to add some tests. I'm creating the PR now as, I'd like people to look over this, and see if they can spot any issues.
Also, `mergeHeads` should be called by the sync code when there are incoming records, @aidanfar0 where's the best place to hook that in?
=> Basic automerging

src/dummyData.ts, src/uiSpecification.ts
Looks like something broke dummyData, this fixes it so we can continue testing new fields.
=> Dummy data setup was broken, fix it

src/sync/state.ts
These errors could theoretically eventually result in the website not being able to
receive updates when a data db updates, but that probably wasn't happening
=> Fixed a buggy check in sync/state.ts causing MaxListenersExceeded errors

bors.toml
Bors needed to be updated for the LTS switch.
=> Update bors for new CI

src/sync/databases.ts
This should mean for tests, we use the in-memory storage (which is faster than using leveldb with node).
=> Add local_pouch_settings to local_state

src/data_storage/merging.test.ts
See test for details, but in simple terms this test has an implicit dependency on the values of the uuids generated. The test should be used for the advanced automerger, which should result in only one head.
=> Comment out flaky test

src/App.tsx, src/gui/components/dashboard/actions.tsx, src/gui/components/project/cardHeaderAction.tsx, src/gui/components/record/form.tsx, src/gui/pages/record-create.tsx, src/reportWebVitals.ts, src/utils/eqTestSupport.ts
This fixes a lot of new 404s that were occuring when trying to create new records.
The 'Add' button on the homepage now separates into different buttons for each viewset,
Technical note on the issue I discussed with James: To fix it,
/new-record/type/:type_id has changed to /new-record/type/:type_id/record/:record_id,
Where there is a redirect from the former to the latter that is where the UUID is generated now (It's a prop in RecordCreate element)
=> Fix variants new record

src/datamodel/database.ts, src/sync/index.test.ts, src/sync/new-project.ts, src/sync/process-initialization.ts
@KateSHENG This should allow you to create local projects for use in the project builder.
@aidanfar0 Can you sanity check this and then merge? There's also a hook for writing up to the conductor, once that's read.
=> Add helper for creating a new local project

src/gui/fields/BasicAutoIncrementer.tsx
The state setting was too late in the call to prevent the ID from being generated multiple times (and hence creating conflicts at the pouch level). Moving right to the top ensures that only one call will be made.
=> Stop auto-ID generation running multiple times

package-lock.json, package.json
It looks like the interface keeps changing, so lock it down to that specific version.
=> Lock @material-ui/data-grid

package-lock.json, package.json, src/index.tsx
This allows using the fallback components where there's no equivalent web standard one.
=> Add capacitor web components

src/data_storage.test.ts, src/data_storage/index.ts, src/data_storage/internals.ts, src/data_storage/merging.test.ts, src/datamodel/core.ts, src/datamodel/database.ts, src/datamodel/typesystem.ts, src/datamodel/ui.ts, src/dummyData.ts, src/gui/components/record/form.tsx, src/projectSpecification.ts, src/uiSpecification.ts
Add another plugin system to handle conversion between attachments and
form data. This should allow for transparent conversion between blobs in
attachments, and their copying to the form data.
=> Add system to handle attachments

src/data_storage/index.ts, src/data_storage/internals.ts, src/data_storage/listeners.ts, src/datamodel/ui.ts, src/gui/components/record/table.tsx
Once the role-based access control is set up, we can look at configuring which roles see deleted records and which don't.
Closes FAIMS3-295.
=> Hide deleted records by default

src/gui/pages/project-settings.tsx, src/uiSpecification.ts
This is a temporary workaround for uploading the project, and will be removed once project upload has been implemented.
@Denubis This produces a bunch of JSON, specifically an array of documents, you could either use fauxton and do this by hand, or possibly use curl to upload everything.
=> Add dumping of metadata db

src/data_storage/index.ts, src/data_storage/internals.ts, src/datamodel/core.ts, src/datamodel/ui.ts, src/gui/components/record/table.tsx
This needs the builder logic to ensure that there's only one HRID.
=> Display a HRID if available

e2e/src/test/java/org/fedarch/faims3/ios/IOSTestSetup.java
So I had some missing capabilities in the browserstack setup. It assumed it was running in MAC, not iOS.
Signed-off-by: riniangreani <rini.angreani@csiro.au>
=> Update IOS browserstack setup with correct capaibilities

src/gui/fields/TakePoint.tsx
For some reason, the error was not a string, convert it pre-emptively.
=> Pre-emptively convert error to string

src/gui/components/record/form.tsx, src/gui/pages/record-create.tsx, src/sync/draft-state.ts
This should make working with relations much easier, as now we can pass around a record id.
=> Generate the record id on form creation, not save

src/sync/connection.ts
Hopefully this should reduce the number of 40* errors seen in the logs.
=> Add skip_setup to pouchdb

src/data_storage/internals.ts
This would only occur when we have the record but not the first head revision, which would only occur when we're still syncing data.
=> Catch possible undefined error

src/gui/fields/TakePhoto.tsx
This should scale the photo taking thing correctly, as well as reduce a click from the android version of "editor"
There are bugs still about overwriting the field value instead of appending to it for multiple photos, as well as work needed to lightbox and be able to delete (and annotate) photos -- but that's for later.
=> a fix for photo scaling in take-photo, and the editing toggle

android/app/src/main/assets/capacitor.config.json, android/app/src/main/res/xml/config.xml, ios/App/App/capacitor.config.json, ios/App/App/config.xml, ios/App/Podfile, package-lock.json, package.json, src/gui/components/authentication/login_form.tsx
The plugin is used via @awesome-cordova-plugins, which used to be called ionic-native. This is because cordova seems to do odd things with how plugins are inported, which @awesome-cordova-plugins wraps in order to provide an easier-to-use interface.
=> Use the cordova inappbrowser plugin

src/gui/components/authentication/login_form.tsx
This reverts commit ee5b5ce2de0cf1cbe647b2bd622c27c8bfa1f130.
The iframe does not work with the android app (it doesn't work either in web, but we can play with cookies to get it to work). Currently the in app browser does not close on command (that will need fixing), the conductor is popping up an alert for now.
=> Revert "Try using iframe for authentication"

src/gui/components/authentication/login_form.tsx
Due to the way the in app browser works, we cannot close it from within the in app browser. Hence we call close once we've processed the token.
=> Close the in app browser when done

src/gui/fields/TakePhoto.tsx
Capacitor's camera plugin does not provide a mimetype, so we must create it from the information we receive.
=> Fix mime type in TakePhoto

src/sync/connection.ts
This may be causing issues with attachments on chrome/safari.
=> Don't set keepalive on pouchdb fetch

src/buildconfig.ts, src/sync/databases.ts
batch_size and batches_limit configure how many documents pouchdb
processes at a single time. The batch_size has been increase to 1000
(from pouchdb's default of 100), to see if that speeds up processing of
synced data.
=> Add envvars to set batch_size and batches_limit

src/sync/process-initialization.ts
We need to recreate the replication connection when logging in, but this
requires notebook-level activation (not autoactivation), so refresh the
page which achieves the same thing for now as a workaround.
=> Fix notebook syncing when logging in

src/data_storage/internals.ts
It appears === does not work on blobs, and so we've been saving the same
value multiple times. Hopefully lodash's isEqual will solve this.
Should fix FAIMS3-367, but needs testing.
=> Use lodash to check whether AVPs are changed

src/buildconfig.ts, src/data_storage/index.ts, src/data_storage/internals.ts, src/data_storage/queries.ts, src/databaseAccess.tsx, src/datamodel/core.ts, src/datamodel/ui.ts, src/gui/components/record/table.tsx, src/users.ts
This will control the visibility of projects and records, there will need to be some (temporary) adjustments to the conductor to set up the couchdb roles, otherwise you won't see anything but your local projects (this will be draft until those are in the conductor).
=> Add filtering based on user

src/sync/databases.ts, src/sync/sync-toggle.ts
There was some confusion between which direction push and pull operated
due to the ordering of databases being passed to sync. By setting the
order such that push is app -> couch and pull couch -> app, the
filtering is now being applied correctly.
There was also a typo for the filter name, which resulted in 404s.
Closes FAIMS3-453 (hopefully).
=> Fix syncing with attachment handling

src/data_storage/index.ts
If for some reason the datadb is not set up, or there is some issue
retrieve data from the datadb, then return an empty list and log the
error.
=> Return empty array when able to load metadata

src/data_storage/internals.ts, src/data_storage/merging.ts, src/datamodel/ui.ts, src/gui/pages/project-list.tsx
This allows comparing with the AVP ID, rather than the data itself
(which is more difficult to do on the fly).
=> Expose AVP IDs and metadata within merging helpers

package.json
This means that serve behaves like the old `npx cap serve`, by rewriting
urls to the app when needed, and not copying the url to the clipboard.
This is needed for the testing with
https://github.com/nolanlawson/fuite.
=> Tell serve to rewrite urls and not use clipboard

src/sync/state.ts
It appears sometimes we're too quick with the automerger so we don't
always have all the required information on hand. Catch and log the
errors for now, to see if we can pick up any patterns that could help
with pre-checks.
=> Catch and log automerge errors

src/gui/components/record/form.tsx, src/sync/draft-state.ts
This should mean whenever the user moves away from the "page", a draft
is saved with the latest data in the form.
Closes FAIMS3-499.
=> Save draft when form unmounted

src/gui/components/metadataRenderer.tsx, src/gui/components/project/cardHeaderAction.tsx, src/gui/components/record/table.tsx, src/gui/pouchHook.ts
It looks like the hook with bind may be leaking memory, use a new
wrapper to avoid needing bind. Hopefully this change appears in fuite.
Don't merge until this has been tested in fuite.
=> Avoid using bind with evented hook

src/sync/index.ts
It appears for datadbs, we were not calling the cancel in the hook
cleanup (this was happening for metadbs). We now directly call the
cancel as we still have the reference to the changes object (which we
lose if we did return the unbound function).
=> Don't bind, call datadb.changes.cancel instead

src/gui/components/authentication/cluster_card.tsx
This is somewhat simple for now, we likely want to allow users to
"logout" without switching, but we don't expect users to be logging out
of the device that much.
=> Add user switcher to login page

src/gui/pages/about-build.tsx, src/sync/data-dump.ts, src/utils.ts
This does not try to do things with visibilities, it simply dumps all
the databases we know about using allDocs.
=> Add a button to dump the contents of all pouchdbs

src/sync/draft-state.ts
Previously, if the only things that changed were annotations, then a
draft would not be created. This adds annotations to the things to be
checked.
=> Check annotations when creating draft

.faimsWords.txt, src/data_storage/internals.ts, src/data_storage/merging.test.ts, src/sync/draft-state.ts
Previously we were not checking if the annotation changed value, so if
the annotation changed value but the data did not, that was not
identified as a change. This adds this check.
=> Add missing check for annotation change

src/index.tsx, src/native_hooks.ts
This should allow for passing tokens via app urls. This requires some additional changes on the conductor side, but hopefully everything should just work.
This does add the assumption that a conductor is not used for more than one listing, which is probably fine.
=> Add simple handler for app urls

src/native_hooks.ts
This should now allow iOS logins to work. This should also work as an alternative for android, and open the native app where possible.
=> Fix origin handling in native hooks

src/gui/components/record/form.tsx
Validation is run on `onBlur` and `onChange` by default by formik. Dropping `onChange` reduces the lag as we're not checking each keypress.
=> Be explicit about when validation is called

android/app/capacitor.build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/assets/capacitor.plugins.json, android/app/src/main/res/xml/file_paths.xml, android/capacitor.settings.gradle, android/fastlane/Fastfile, ios/App/Podfile, package-lock.json, package.json, src/gui/pages/about-build.tsx, src/sync/data-dump.ts, src/utils/downloadShare.ts
This seems to be a better supported way to get the data off the device than trying to use downloads (which seem to be a problem on Android, and for which Capacitor currently lacks support for).
=> Add sharing of data dump

src/store.tsx
For reasons that still remain unclear, sometime the pouchdb code signals to react that it is ready, but it remains still in the setup phase. This adds an additional 10 second timeout once the pouchdb code signals it is ready, just to avoid this issue (which only seems to occur on refreshes). This isn't a true fix, but should be a good-enough workaround.
See FAIMS3-587 and FAIMS3-496 for details of the issue.
=> Add an addition timeout to ensure refresh works

src/data_storage/index.ts
Datagrid state appears to be lost every time we update the record list, see if sorting the list makes datagrid happy.
Possible fix for FAIMS3-562.
=> Try to see if sorting makes datagrid happy

src/gui/components/record/RecordData.tsx, src/gui/components/record/form.tsx, src/gui/components/record/read_view.tsx, src/gui/pages/record-create.tsx, src/sync/draft-state.ts
There was a missing call to switch off flashing once the save was completed, add it in, and remove unused props which may confuse the issue.
Possible fix for FAIMS3-520.
=> Add possible fix for draft over flashing

src/utils/downloadShare.ts
It seems there's an issue sharing data in the Cache directory, try the External one.
See FAIMS3-547.
=> Switch to saving data in External path

bors.toml
Point bors at node 16 version, rather than node LTS version.
=> Bors needs updating for the node 16 changes

src/gui/components/record/formButton.tsx
=> fix: remove continue button from record form in favour of mobile stepper

src/datamodel/core.ts, src/sync/connection.ts, src/sync/process-initialization.ts, src/utils/status.tsx
This should hopefully tell users when the token no longer is working with CouchDB (e.g. the token is expired, the server has changed signing keys).
=> Notify user when there are token issues

src/gui/components/record/table.tsx
It's possible the props are behaving in such as way as to cause the table to rerender.
=> Log what is being passed to RecordTable

src/users.ts
While we switched users for the purposes of who appeared as author of revisions, we did not previously change the sync connection, this adds that change.
=> Switch user for listing purposes

src/datamodel/autoincrement.ts, src/gui/components/autoincrement/edit-form.tsx
Previously if a range was being used, then the stop value could not be decreased. This removes that restriction.
See FAIMS3-643.
=> Allow autoincrement stop values to be decreased

src/native_hooks.ts
For some reason, Safari manages to extract the host but Firefox and Chrome do not, add handling of the non-Safari case.
Should provide a workaround for FAIMS3-631.
=> Get app url parsed on non-Safari browsers

src/gui/components/workspace/notebooks.tsx
bug: fix non-plural 'notebook' with 0 notebooks
@lmannering two tiny changes for you to look over. Not sure if I did it correctly, but I've tested it locally.
=> feat: disable and set default tab to available if activated empty

src/datamodel/typesystem.ts
It appears BigUint64Array requires that the data be aligned to 8 bytes (rather than accepting less and having 0 values elsewhere). Switch to Uint8Array which should fix this.
=> Use Uint8Array for comparing blobs

src/datamodel/autoincrement.ts
Once a range is fully used, there's not much need to keep it around expect for keeping users in the loop. Allow users to delete them. This also resolves a issue where having a fully used range prevented the creation of a new range.
Fixes FAIMS3-644.
=> Allow users to delete fully used ranges

src/sync/draft-state.ts
This should allow us to check why drafts aren't removed sometimes.
For FAIMS3-674.
=> Log when draft storage isn't cleared

src/gui/components/record/form.tsx
It appears that the CSS for the toast crashed due to the use of 'warnings' rather than 'warning'. This does not fix the issue causing the data to be unable to be loaded.
=> Fix status typo

src/datamodel/database.ts, src/gui/components/authentication/cluster_card.tsx, src/users.ts
The state of the app wasn't fully switching between different users, remove duplicate information stored and make the switching flow cleaner.
Should close FAIMS3-546.
=> Fix current user state for user switcher bug

src/gui/components/notebook/add_record_by_type.tsx, src/gui/fields/qrcode/QRCodeFormField.tsx
Adds a button to the project page to allow scanning a QR code. If the scan matches a valid record field value, then it will navigate to that record. 
Configured by adding 
```JSON
meta: {
"showQRCodeButton": "true"
}
```
to the project metadata. 
(as yet  untested on mobile).
=> Jump to record by scanning QR code

src/datamodel/autoincrement.ts, src/gui/components/autoincrement/edit-form.tsx
We were setting `using=false` too early, do the switch on commit so that the component and form are in the right state.
For FAIMS3-643.
=> Fix autoinc disable flow

.faimsWords.txt, .gitignore, jsdoc.config.json, package-lock.json, package.json, src/data_storage/index.ts, src/datamodel/core.ts, src/gui/components/qrcode/DisplayQR.tsx, src/gui/pouchHook.ts
Use JSDoc to generate documentation, start the process of adding structured comments to code.
This will be an ongoing task but this at least sets up the machinery to generate useful code documentation.
=> Add JSDoc to build code documentation

src/gui/components/record/view.tsx, src/gui/components/validation.ts, src/projectMetadata.test.ts
Errors in forms are not highlighted sometimes and we have an error alert that just says that there is an error somewhere. Here we add more detail to that alert and also make sure that required fields are validated (currently only if they also have required in the validation schema).
=> Provide more detail on errors

package-lock.json, package.json, src/gui/components/record/form.tsx, src/gui/components/record/relationships/RelatedInformation.tsx, src/gui/components/record/relationships/field_level_links/datagrid.tsx, src/gui/components/record/relationships/record_links.tsx, src/gui/components/record/view.tsx, src/gui/components/ui/record_link.tsx, src/gui/fields/RelatedRecordSelector.tsx, src/gui/pages/record-create.tsx, src/gui/pages/record.tsx, src/sync/draft-state.ts, src/sync/index.ts
For a record that is a child of some parent record, the 'Publish and New' button should create a new child of the same parent. At the moment, it doesn't. 
In the process of fixing, I've also found the problem that caused drafts to be left behind when records are saved.  Included here was a bug that left behind global timers that would try to save records at regular intervals.  There may still be some left behind drafts but should be many fewer than before. 
The publish and new behaviour turned out to be a bug.  The identity of the relation field was supposed to be passed to the next page but it wasn't being passed properly.  This broke subsequent logic to create the new child record.  In the end this was a one line fix.
=> Fixing 'Publish and New' for child records

app/vite.config.ts, designer/package.json, designer/vite.config.ts, package.json
Both `app` and `designer` use vite and start up on random ports. Fix the ports at 5000 for the app and 5010 for the designer so we don't get confused.
=> Ensure different known ports for designer and app

app/src/gui/components/record/RecordData.tsx
Uncovered a crash condition while testing a notebook. Not sure why it wasn't evident before but one file mistakenly imported useNavigate from react-router rather than react-router-dom causing a crash.
=> get useNavigate from react-router-dom not react-router

infrastructure/aws-cdk/.gitignore, infrastructure/aws-cdk/README.md, infrastructure/aws-cdk/lib/components/conductor.ts, infrastructure/aws-cdk/lib/components/couch-db.ts, infrastructure/aws-cdk/lib/components/networking.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts
[BSS-203](https://jira.csiro.au/browse/BSS-203)
Consolidates the two application load balancers into one. Uses target groups with domain name conditions to handle routing to the correct target group. Adds HTTP redirect (try this in browser and you'll see auto redirect to https e.g. http://faims.bss.nbic.cloud/ ). 
Save costs by reducing redundancy in load balancers. HTTP is not suitable for our application so automatically redirecting is good for users to transparently use the correct protocol.
See our deployment (contact dev for URL if needed) - this is deployed with updated version. Check conductor and couch endpoints operate properly. Test HTTP redirect. 
https://jira.csiro.au/browse/BSS-219 (update priority configuration) 
https://jira.csiro.au/browse/BSS-218 (fix issue with 404 on …
=> feat: BSS-203 consolidate application load balancers

infrastructure/aws-cdk/README.md, infrastructure/aws-cdk/configs/sample.json, infrastructure/aws-cdk/lib/components/couch-db.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts, infrastructure/aws-cdk/package.json
[BSS-220](https://jira.csiro.au/browse/BSS-220)
- Installs cloud watch agent onto instance in user data
- Collects logs from mounted data volume at `data_path/couch.log`
- Reports system metrics using cloud watch agent, then adds
-  Dashboard to visualise
- Alarms for configurable thresholds for key metrics
- Subscription to email alerts for alarming state
-  Adds init-api command to package.json to quickly curl the initialise endpoint
- Deployment should be up to date soon
- Might need to clear application storage due to redeployment
=> feat: BSS-220 Implement monitoring, dashboard, alarming and logging for EC2 Couch instance

infrastructure/aws-cdk/README.md, infrastructure/aws-cdk/bin/aws-cdk-faims-infra.ts, infrastructure/aws-cdk/configs/sample.json, infrastructure/aws-cdk/lib/faims-infra-stack.ts
Adds the stack name to the main configuration option. Documentation updated etc.
**Note**: changing the stack name will force redeployment. But changing this namespace allows you to have multiple deployments in a single account.
=> feat: bss-229 add stack name to configuration

.github/workflows/publish-conductor.yml, api/BuildDockerfile
Merges updated work on the docker publish process with existing `api/.github/workflows/docker-image` workflow. Publishes to the GitHub container registry instead of DockerHub. 
Also fixes an issue where the `views` directory was inaccessible within the published API docker image. Fixes by copying into the appropriate location (though it's a little hacky). 
See actions for successful build. I have also confirmed the image is working on a deployment.
=> build: publish to github container registry

app/src/App.tsx, app/src/gui/components/notebook/settings/activation-switch.tsx, app/src/gui/components/ui/Faims_Attachment_Manager_Dialog.test.tsx, app/src/gui/components/ui/Faims_Attachment_Manager_Dialog.tsx, app/src/gui/components/ui/Faims_Dialog.tsx, app/src/gui/components/ui/Reusable_Dialog.tsx, app/src/gui/fields/FileUploader.tsx, app/src/gui/fields/TakePhoto.tsx
Parent Jira Issue:  https://jira.csiro.au/browse/BSS-112
Subtask - https://jira.csiro.au/browse/BSS-256
- Created a ReusableDialog component to standardize the layout and styling of dialog boxes across the application.
- The component is highly customizable, allowing for the easy addition of an icon, title, primary action button, and cancel button, which would make it easier to draft BSS Design related dialogs as exists in figma designs
-  The dialog is responsive, ensuring usability across different screen sizes.
- New Reusable-Dialog Component Created
- Refactored the NotebookActivationSwitch component to utilize the new ReusableDialog.
- The NotebookActivationSwitch is in alignement with BSS Activate Survey Design dialog.
- Navigate to notebooks list.
- Click Activate on any of …
=> Reusable dialog component and enhacements

api/src/buildconfig.ts, app/src/buildconfig.test.ts, app/src/buildconfig.ts, app/src/gui/layout/appBar.tsx, infrastructure/aws-cdk/cdk.json, infrastructure/aws-cdk/lib/components/conductor.ts
[BSS-224](https://jira.csiro.au/browse/BSS-224)
Fixes missing environment variable in conductor API configuration for AWS deployment. 
Refactors default conductor URLs to constants in the app and api code. 
Adds doc strings for conductor URL split method and handles error conditions more durably including filtering out empty values which could result from trailing commas, and warning under either empty string or empty list conditions. Falls through to the default value if the length of the list after splitting and filtering out empty values is zero, such as in the case where the environment variable is an empty string. 
1. Testing changes to conductor URL splitting logic: I added unit tests for this function. See `cd app && npm i && npx vitest buildconfig`.
2. Testing AWS deployment - not …
=> fix: missing conductor_url in aws code and improving handling of error/warn conditions

app/src/sync/metadata.ts
[BSS-309](https://jira.csiro.au/browse/BSS-309)
There was a bunch of errors being thrown on app load which was being caused by the notebook metadata fetch pinging the incorrect url. 
- updated api URL to be fixed.
- ensure you are logged in and have at least one activated notebook (survey).
- monitor console for errors.
This was caused by the previous notebook rename PR.
=> fix: api url in metadata fetch

api/views/home.handlebars, api/views/notebook-landing.handlebars
In Conductor, copy to clipboard was not working on Firefox. 
Remove browser dependent check that is not required, now works cross-browser.
In Conductor on the main page, click "Copy Token". On a notebook page, create an 
invite for the notebook and click "Copy Registration URL".
=> Copy to clipboard not working on Firefox

library/data-model/src/types.ts
Proposed set of interfaces / endpoints for new functions in the new survey API.
See `library/data-model/src/types.ts` for the new interfaces. 
```typescript 
// ================== MOCKS FOR NEW SURVEY API ===============
// TODO cleanup
// Template database item
// These are the fields used to instantiate the item
type UiSpecificationType = object;
export interface TemplateDbDocumentDetails {
name: string;
ui_specification: UiSpecificationType;
}
// Once it's in the DB we'll have a _id field as well
export interface TemplateDbDocument extends TemplateDbDocumentDetails {
_id: string;
}
// Conductor CRUD API
// Create new template
// To create a new template
// POST /templates
// Expects JSON Payload
interface PostCreateTemplateInput extends TemplateDbDocumentDetails {}
interface …
```
=> dev: new survey API mock interfaces

app/src/gui/components/notebook/add_record_by_type.tsx
None
Fix a bug introduced in previous PR
Call to getMetadataValue used the short `_id` rather than the longer `project_id` that includes the listing id. Only in one place (getting the QRCode field setting). 
Load up a notebook field and notice the lack of errors.
=> Fix/Call to getMetadataValue uses _id instead of project_id

api/docker-compose.yml
None
Docker compose file was referencing the old docker image and had an extra run command that prevented it working.
Reference the new conductor docker image and remove the run command.
In the APi folder run:
```sh
docker compose build
docker compose up -d
```
=> Fix docker compose for deployment

api/package.json, package-lock.json
This package was not in package.json. Now it is.
=> add express-async-errors

app/src/drafts.ts, app/src/gui/components/notebook/delete.tsx, app/src/gui/components/notebook/draft_table.tsx, app/src/gui/components/notebook/index.tsx, app/src/gui/components/notebook/record_table.tsx, app/src/gui/components/ui/tab-grid.tsx, app/src/gui/fields/TakePoint.tsx, app/src/gui/fields/maps/MapWrapper.tsx, app/src/gui/pages/notebook.tsx, app/src/sync/draft-storage.ts, app/src/utils/status.tsx, designer/src/fields.tsx
[BSS-399](https://jira.csiro.com/browse/BSS-399)
Deleting draft records was not working, the dialog stayed open after clicking delete and the record stayed in the list.
The bug was with the refresh of the record lists. Deletion was happening but a  previous PR had changed the callback
function that was supposed to trigger refresh.   The solution was actually to move the refresh down to the record
table component.
The same problem existed with deleting records. This is also now fixed.
I've also removed a few bits of debugging output and fixed some warnings that showed up during testing. 
- TakePoint fields were passing the helperText property on to the Button component causing a  warning. This was because all properties from the configuration were just passed in blindly. I changed this to …
=> Fix draft deletion

app/src/gui/components/record/fields.tsx, app/src/gui/components/record/form.tsx, app/src/gui/components/record/view.tsx, app/src/gui/fields/ActionButton.tsx, app/src/gui/fields/Address.tsx, app/src/gui/fields/BasicAutoIncrementer.tsx, app/src/gui/fields/DateTimeNow.tsx, app/src/gui/fields/FileUploader.tsx, app/src/gui/fields/RelatedRecordSelector.tsx, app/src/gui/fields/TakePhoto.tsx, app/src/gui/fields/TakePoint.tsx, app/src/gui/fields/TemplatedStringField.tsx, app/src/gui/fields/maps/MapFormField.tsx, app/src/gui/fields/multiselect.tsx, app/src/gui/fields/qrcode/QRCodeFormField.tsx, app/src/gui/fields/radio.tsx, app/src/gui/fields/select.tsx, app/src/gui/fields/selectadvanced.tsx, app/src/gui/layout/appBar.tsx, designer/src/fields.tsx
[BSS-352](https://jira.csiro.com/browse/BSS-352)
If a photo field is required we still show an error message after adding a photo in some cases (rapid impact prototype).   This seems to be due to when validation runs on the form - it doesn't run until a change is triggered and adding a photo doesn't trigger a change.
It turns out that validation was not being triggered when we set field values because a third argument to `setFieldValue` was missing.  If this is true, then validation is triggered when the field is set.   All calls have been updated.  In a few cases, notably select, I had to do more work to ensure that it was called at the right time. 
Some fields are directly implemented via the Formik text field and so I've not changed them. TextField seems to work and I think the others …
=> Fix: Field validation timing

api/couchdb/local.ini.dist, infrastructure/aws-cdk/.vscode/tasks.json, infrastructure/aws-cdk/README.md, infrastructure/aws-cdk/lib/components/conductor.ts, infrastructure/aws-cdk/lib/components/couch-db.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts
- adds configurable couch version tag and pins to 3.3.3 by default
- the above provides a workaround to the `jwt_auth` breaking change where 'exp' is a mandatory claim - see JIRA ticket to implement and integrate token refresh. Issue here (https://github.com/apache/couchdb/issues/5046)
- updates the user data couch configuration to inject the cookie secret from the FAIMS_COOKIE_SECRET shared AWS Secret Manager, rather than hardcoding. The dist file was copied which included a placeholder secret value which was replaced at build time with a secret.
AWS deployment is up to date with these changes including re-creating a new instance. 
It might be worth extending the initdb API - however we would need to ensure that the chttpd_auth secret configuration is not required to enable API …
=> fix(aws): jwt auth backwards compatibility (exp claim) and chttpd_auth security improvements

.github/workflows/build-lint.yml, api/package.json, api/src/api/notebooks.ts, api/src/api/templates.ts, api/src/api/users.ts, api/src/api/utilities.ts, api/src/core.ts, api/src/utils/patchExpressAsync.js, infrastructure/aws-cdk/package.json, package-lock.json, turbo.json
- changes require('express-async-errors') to instead hardcode the actual patch into a file, and export a function - this resolves the issue where the require was being cached causing improper patching, regressing the async timeout on API unit tests
- fixes merge issue which removed the conductor short code prefix from the listings object in info 
- adds the API unit tests as a turbo config, the other tests run but don't currently pass due to existing issues. To run unit tests, ensure `.env` file is valid and then run `turbo run test --filter=@faims3/api`
- updates github action to run this on PR
=> fix: fix express async issue, return API unit tests, add turbo config

app/src/gui/components/ui/heading-grid.tsx, app/src/gui/components/ui/tab-grid.tsx, app/src/gui/components/workspace/notebooks.tsx
Fixes mui data grid display issues due to stale pagination model (which was fixing the page size at 0) + bubble theme colouring hiding the folder icon. 
Try different combinations of theme + notebook list layout and check that items render in the available and active sections correctly. 
As a consequence of changing from 'secondary' to 'primary' as the theme colour, changes the colour of the folder icon on the default theme for active notebooks to green.
=> fix: fixing improper display of notebooks in headings mode

app/src/gui/components/notebook/record_table.tsx, app/src/users.ts, library/data-model/src/data_storage/internals.ts
Closes https://jira.csiro.au/browse/BSS-453
User could not see records of other users even if admin on notebook. 
I also wrapped the record fetch in useQuery to continue alignment with new style - chose a very conservative cache approach since there's no obvious trigger to rely on to refresh the record list.
Offending code was `src/users.ts` in `app` 
Notably the app was looking for cluster-admin on a notebook which doesn't exist as a role. `admin` is the correct role name. 
@stevecassidy  looking for insight on how to derive this role - given the roles and actions are customisable within the notebook spec, right? 
Also, shouldn't this be enforced in the DB and the client should not need to filter?
=> fix: correct client side record filtering

app/src/gui/components/workspace/CreateNewSurvey.tsx, app/src/gui/components/workspace/notebooks.tsx, app/src/users.ts, app/src/utils/useGetCurrentUser.tsx
[BSS-465](https://jira.csiro.au/browse/BSS-465)
Updates the create new survey workflows to respect authorisation. Keeping in mind this is not currently well defined because there is no sense of 'active listing'. This is the behaviour proposed and implemented.
- on the surveys page, if there is ANY listing in which the active user for that listing has creation permissions, show the button
- on the create new <survey> page, filter the listings to only show listings for which the user has permission
Create a user with permission, and one without, and check that things render as expected. Noting that you will need to manually refresh tokens using the Workspace refresh button to get the updated tokens.
=> feat: adding permission handling into create new survey workflow views

app/src/sync/initialize.ts
[BSS-477](https://jira.csiro.au/browse/BSS-477)
Users with an existing auth DB had records with no parsedToken field. The updated versions of the app expect this field to exist. This resulted in `cannot read property <x> of undefined` errors which crashed the app. 
This PR adds a step to the initialisation logic which runs once on app startup (this is refresh on browser, or app open on phones). 
This initialisation code performs a validation of the contents of the local auth DB, fixing things were it can. It makes the best attempt possible to make sure the auth DB is valid, and tries to make no assumptions about it's contents. 
This covers
```typescript
* This function performs several maintenance tasks on the local auth database:
* 1. Validates that all stored auth documents correspond …
```
=> fix: adding initialisation step to validate local auth DB and inject parsedTokens where unavailable

designer/src/components/field-editor.tsx
None
Still getting a build error in CI. This time remove slotProps which it claims does not
belong on Accordian contrary to the documentation and examples. 
Change means that each field will still be mounted on being closed, should not be 
an issue. 
Merge into main and hope that the CI build works
=> Remove slotprops to fix CI build

api/src/routes.ts, api/views/cluster-users.handlebars
[BSS-467](https://jira.csiro.com/browse/BSS-467)
In Conductor, changing the roles of a user on the /users page didn't seem to work properly. Here we
fix this.
The fix is to the display of roles, existing code did not properly display whether a user had these roles
or not.  Toggling the roles worked but since the page wasn't displaying them, it was confusing and
unuseable. 
Visit the /users page on Conductor where you have more than one user, you should be able to add roles
and refresh the page to see that they persist.
Note, there is a quirk in that 'cluster-admin'  implies notebook creation so if you toggle admin for a user
and refresh the page, create notebooks will be checked.  I decided not to write code to be any fancier 
than this but added a note into the page.
=> Fix display and toggle of user roles

app/src/gui/components/record/form.tsx, app/src/gui/fields/TakePhoto.tsx, app/src/lib/form-utils.ts
None
The record completion progress bar was not working. It was counting
the percentiage of all fields in the uiSpec rather than those in 
the current form. 
Also fixed a warning about keys in the image list.
Progress bar should now show 100% completion when all required fields
are filled in.
Note, I've left the update of the progress bar inside the render method since
there is no other place to put it that would work but it is updating the parent
state inside the render method which is bad form - get a warning if you refresh
the page when on the form but not in normal flow.
=> Fix form progress bar count

app/src/context/functions.tsx, app/src/context/projects-context.tsx, app/src/gui/components/authentication/auth_return.tsx, app/src/gui/components/notebook/record_table.tsx, app/src/gui/components/workspace/notebooks.tsx
[BSS-451](https://jira.csiro.au/browse/BSS-451)
Initialise surveys on page load and button to trigger remote sync manually.
- added init/sync projects functions to context provider
- added init project to run on login
- added sync projects button
- made tab default to 2 if no activated projects
1. Log out of app
2. Log into app
3. Check that surveys are visible without refresh
4. (optional) Repeat 1-3 but clearing cache after logout
5. Add survey in conductor
6. Hit refresh button and ensure it becomes visible
=> feat: initialise surveys

Dockerfile, app/package.json, app/src/gui/fields/TakePhoto.tsx, package.json
Moves the 'label' text from the button itself to a <\h3\> component. Moves the helper text into a \<p\> element which helps with size and spacing. The button is adorned with a camera icon, and uses a contained style which makes it more visible. 
@stevecassidy worth considering if this change will negatively impact any existing notebooks which rely on the button text being the label - I didn't really personally think this was very helpful as the button always does the same thing, in any notebook, it 'takes a photo'.
=> feat: make photo fields more prominent

app/src/gui/pages/shortcode.tsx
We were having issues on iOS with a single listing of the prefix selector obscuring input on small/weird scaling displays. This is a **temporary fix** to facilitate user testing which conditionally renders the dropdown only when there is actually multiple listings to choose from. This allows the input field to scale to fill the whole available width.
Reasonable scaling example
Exaggerated large scaling example
=> fix: only show prefix selector if more than one listing

app/src/gui/components/notebook/settings/activation-switch.tsx, app/src/gui/components/ui/heading-grid.tsx, app/src/gui/components/ui/tab-grid.tsx, app/src/gui/components/workspace/notebooks.tsx, app/src/gui/pages/workspace.tsx
Update the wording as per discussion - make these values consistent and configurable to make edits faster in the future.
=> feat: improved wording for active and not-active 

app/src/gui/fields/maps/MapFormField.tsx, app/src/gui/fields/maps/MapWrapper.tsx
This PR enables a center to be defined while still requesting and gracefully handling a current location call (which prompts permission check). This is to allow user testing with the following workflow. 
This might be temporary since in reality we probably don't need to ask for the user's location if we don't intend to actually use it. 
Technical changes include:
- useEffect with useRef to only run once
- use const variables instead of modifying readonly props
- only store get location result if center is not defined in props
- add alerts for warning conditions such as not being able to access location
- add alerts for using default map center location (no current location available AND no configured center location) - this defaults to Sydney
Try different permutations of permissions yes, …
=> feat: improved permission handling for MapFormField

app/src/gui/components/authentication/oneServerLanding.tsx, app/src/gui/components/authentication/shortCodeOnly.tsx, app/src/gui/fields/qrcode/QRCodeFormField.tsx, app/src/gui/pages/shortcode.tsx, app/src/gui/pages/signin.tsx
During user testing it became apparent most users are struggling with the onboarding due to a cluttered / unclear workflow to get started. This PR introduces a special case component which triggers under these conditions
- not signed in to ANY listing
- there is only one listing
- the token is not being loaded from local storage (to try and minimise flickering)
- QR scanning logic is reused, button props are passed through to enable styling of the QR buttons - only enabled on mobile platforms
Note: the implementation is not very high quality - I copy and pasted other components to try and not risk disturbing any existing stuff. I would like to clean this up later, probably when we handle the 'active persona' work later. 
@stevecassidy  if you could, would be great if you could check that …
=> feat: simplified new user onboarding for single listing special case

app/src/constants/privateRouter.tsx, app/src/gui/components/record/form.tsx
None
The app was not updating saved drafts as it should.  On IOS and Android, it would not save a photo after it was captured. 
Very obscure bugs. 
- draft saving is triggered by a call in form.tsx that had been placed after a conditional for inline forms, so wasn't being called for inline forms
- photo saving was being interrupted by too frequent re-renders of the RecordForm component that lost data because it happened between GetPhoto returning and the data being stored.
Check Android and Apple builds, see how you are able to take photos, notice how the draft is updated if you quit out of the form without saving.
OMG! OMG! OMG!
=> Fix bugs saving drafts and storing photos

app/src/gui/components/autoincrement/edit-form.test.tsx, app/src/gui/components/autoincrement/edit-form.tsx, app/src/gui/components/notebook/index.tsx, app/src/gui/components/notebook/settings/auto_incrementers.tsx, app/src/gui/fields/BasicAutoIncrementer.tsx, designer/src/state/migrateNotebook.test.ts, designer/src/state/migrateNotebook.ts
None
Auto increment fields are used to generate human readable IDs for records.  There 
was a bug that caused them to not work if the initial value of the field was 
set to "" as it was in the designer. 
These fields require that a range of numbers is set for the device before records can
be properly created.  The past behaviour was to notice when they weren't set up but
not really help the user set them.
- Deals with the case when the initial value is ""
- Turn the range setting form into a popup dialog
- trigger the popup if a user tries to create a record without the ranges being set
Open a notebook with an auto increment field configured, eg. [Campus Survey](https://github.com/FAIMS/FAIMS3-Notebook-Campus-Survey-Demo).  Try to create
a record after activating the notebook, you should …
=> Improve Auto-incrementers

app/src/gui/components/notebook/overview_map.tsx
None
The overview map had a fixed center point somewhere in Africa.  More useful to move it
to the current location.
- get the current location when displaying the overview map, use it as the center point 
- add a marker (+) at the current location on the map
Open a notebook with geo-locations (BSS) and view the Map. See the cross at your current location.
Move the map, click the circle 'center map' button and see it center the map on your location.
=> get current location for overview map center, put a marker there

app/src/context/functions.tsx, app/src/context/projects-context.tsx
[BSS-548](https://jira.csiro.au/browse/BSS-548)
Projects list not working while offline.
- Added function to update local database with projects list on both sync and init
1. Ensure the projects list works without internet
I believe the context provider was already pulling in the local projects it was just empty as the update local function was lost in an update.
=> fix: offline projects list :bug:

.github/workflows/appstore-deploy.yml, .github/workflows/fieldmark-google-play-prod.yml
None
Need a different configuration variable for production build server.
Adds PRODUCTION_CONDUCTOR_URL to production builds.
=> Different conductor URL for production builds

app/src/conditionals.test.ts, app/src/conditionals.ts, designer/src/components/condition.tsx, package-lock.json
[634](https://jira.csiro.au/browse/BSS-634)
Implements the following designer conditions - necessary for the updated rapid impact (as well as subsequent detailed surveys). 
- contains (the list contains this value)
- does not contain (the list does not contain this value/ it is not selected)
- contains regex (contains at least one selection matching this value)
- does not contain regex (the list does not contain any selection matching this value)
The values in the list and the specified filter value are white space stripped, but I haven't touched any existing work to ensure I don't effect legacy notebooks relying on this non-sanitised behaviour.
I implemented unit tests but they won't run due to broader issues in the app tests. However you can specifically run them with. 
```bash
cd app …
```
=> feat: multi select conditions

app/src/gui/components/record/form.tsx
[BSS-633](https://jira.csiro.au/browse/BSS-633)
Previously, if you had a field which was not visible because of conditional logic (at the section or the field level), the `required` constraint was still enforced by the yup validation schema regardless of whether the field was visible. This meant that you could create states where it was impossible for a user to successfully/accurately fill out the form if you have fields which are **required and conditionally visible**. 
Make `required` only enforced at the schema validation level for fields which are visible, taking into account section and field level constraints. 
The form logic is very fragile so I attempted to make a minimal intervention which solves the problem. This intervention takes over validation at the whole of Form level by …
=> feat: conditional error filtering

api/src/buildconfig.ts, api/src/services/keyService.ts, infrastructure/aws-cdk/lib/components/front-end.ts
Previously the function was being called which threw an error if the file path was not specified. Given the file path does not always need to be specified this only calls the underlying function in the key source generation. This happens anyway during build config setup due to the creation of the key source service. This prevents an error in the latest nbic deployment.
Also updating some CSP settings for AWS deployment for designer fixing a bug with notebook upload.
=> fix: stopping key file path reading when key source is AWS_KM

app/src/gui/fields/multiselect.tsx, designer/src/components/Fields/OptionsEditor.tsx, designer/src/components/field-editor.tsx, designer/src/fields.tsx, designer/src/state/initial.ts
Multi select as list:
[BSS-573](https://jira.csiro.au/browse/BSS-573)
Allow reordering:
[BSS-644](https://jira.csiro.au/browse/BSS-644)
Allow editing: 
[BSS-643](https://jira.csiro.au/browse/BSS-643)
Updating multi select component in App, adding expandedChecklist option, implementing in designer, adding move and edit capabilities for options while there.
See the new checkbox in the designer for multi-select. 
See the move up/down and edit capabilities.
Create a notebook with multi selects of both types (true/false) and check it renders properly.
=> feat: option to render multi select as expanded check list, edit and move options

app/bin/prebuildConfig.sh
Need to release a new version on IOS so bump it's version number.
=> Bump IOS to 1.0.5 for new release

api/src/buildconfig.ts, api/src/routes.ts, api/views/home.handlebars, api/views/layouts/main.handlebars, api/views/notebook-landing.handlebars, api/views/notebooks.handlebars
None
For the new release of Fieldmark we want a slightly nicer home page on Conductor. 
Removes the unused return to app button and list of notebook roles. Adds links
to the various apps if configured.  
Add the following to `api/.env`:
```bash
WEBAPP_PUBLIC_URL=http://localhost:3000
ANDROID_APP_PUBLIC_URL=https://play.google.com/store/apps/details?id=org.fedarch.faims3
IOS_APP_PUBLIC_URL=https://apps.apple.com/au/app/fieldmark/id1592632372
DESIGNER_URL=https://designer.testing.fieldmark.app
```
You should see these links on the Conductor home page.
Will soon be superceded by "New Conductor".
=> Remove useless stuff from home page and add links to web/mobile apps if available.

designer/src/components/design-panel.tsx, designer/src/components/form-editor.tsx, designer/src/components/section-editor.tsx
[BSS-640](https://jira.csiro.au/browse/BSS-640)
This PR fixes a bug in the designer where switching from the second section of a form to a form with only one section incorrectly displays an empty form with the message, *"Form has been created. Add a section to get started."*
- **Reset activeStep:**
- Added a `useEffect` hook to reset `activeStep` to `0` when `viewSetId` changes
- **Conditional Rendering Fix:**  
- Updated the rendering logic to check `sections.length === 0` instead of relying on `activeStep` to prevent incorrect state interpretation when switching tabs.
- If `sections.length === 0`, the message *"Form has been created. Add a section to get started."* is displayed.  
- Otherwise, the `SectionEditor` component renders the active section correctly. 
1. Run Designer.
2. Open …
=> Fix: Designer bug when switching forms

api/package.json, app/bin/prebuildConfig.sh, app/package.json, package.json
None
Increments the version number to 1.1.0 for future builds.  
Removes a special case version number for IOS,  now all apps will be on the same version number.
The rationale for doing this now is to avoid confusion with nightly builds pushed to the app stores. These are now clearly pre-release 1.1.0 builds rather than post release 1.0.0.
=> Increment version to 1.1.0, remove ios specific version string

app/ios/App/App/Info.plist, designer/src/components/field-editor.tsx, designer/src/components/form-editor.tsx
[BSS-681](https://jira.csiro.au/browse/BSS-681)
This PR improves the designer's _section stepper_ by ensuring sections become scrollable there are too many to fit within the viewport's horizontal width.
Additionally, it:
- Ensures **selected steps stay visible** when the viewport resizes.
- **Shows a gradient indicator at the right edge** when scrolling is possible.
- **Keep the stepper's width** to at least **70% of the screen** until scrolling is necessary.
- **Make sure steps have a minimum spacing** (`120px`).
- **Use `scrollIntoView()`** to keep the active step visible when switching steps or resizing.
- **Add a scroll gradient indicator** when scrolling is possible.
1. Run the designer and open the design tab after loading a template or creating one.
2. **Check behaviour with few …
=> Add horizontal scrolling to sections in the designer

api/.env.dist, app/src/context/slices/authSlice.ts, app/src/drafts.ts, app/src/gui/components/notebook/datagrid_toolbar.tsx, app/src/gui/components/notebook/draft_tab_badge.tsx, app/src/gui/components/notebook/draft_table.tsx, app/src/gui/components/notebook/index.tsx, app/src/gui/components/notebook/record_table.tsx, app/src/sync/connection.ts, app/src/sync/databases.ts, app/src/sync/draft-storage.ts, app/src/sync/index.ts, app/src/sync/process-initialization.ts, app/src/sync/projects.ts, app/src/sync/sync-toggle.ts, app/src/users.ts, app/src/utils/apiOperations/client.tsx, app/src/utils/customHooks.tsx, library/data-model/src/data_storage/index.ts, package-lock.json
[BSS-708](https://jira.csiro.au/browse/BSS-708)
[BSS-712](https://jira.csiro.au/browse/BSS-712)
Fixes logical issue with record filtering for my vs other responses. 
Moved record listing logic into reusable custom hook which is smarter about caching, memoisation etc. 
Makes draft and normal record management more sensible with custom hooks for both.
Moves the record fetching to the top level so it can be done once and memoised.
Fixes the issue which was that at no point was the record table actually being configured to properly filter based on mine vs others. 
Added auto refresh every 10 seconds for the list to ensure it stays fresh.
Fixes or at least mitigates this bug https://jira.csiro.au/browse/BSS-712 
This was principally two main bugs
1. the options {push:{}, pull:{}} were used as …
=> fix: my vs other record listing, pouch, sync, drafts

api/src/auth_routes.ts, api/test/conductor.test.ts, api/views/auth.handlebars, api/views/layouts/auth.handlebars, api/views/layouts/fallback.handlebars, api/views/layouts/main.handlebars, api/views/register.handlebars, designer/src/components/section-editor.tsx, designer/src/state/uiSpec-reducer.ts
[BSS-709](https://jira.csiro.au/browse/BSS-709)
Refreshes the appearance of the login/register routes. 
Eventually the other handlebars views will be deprecated (see #1257)
Notably
- more modern/minimalist appearance
- reusing CSS styling classes
- adding an auth layout which has common CSS (a pathway towards theming but not implementing here)
- removing the redundant nav bar, log out button etc
View and functionally test the login and register conductor pages.
Theming not implemented here - so went with consistency with Fieldmark colours but tried to keep it minimalist so it doesn't stand out for BSS use case. Can override the root CSS colours (since these are variables) in another PR.
Login
Register
Register
Login
=> feat: refreshed UX for auth routes

app/src/utils/formUtilities.ts, designer/src/components/TemplateBuilder.tsx
[BSS-714](https://jira.csiro.au/browse/BSS-714)
For our use case, just disabling the escape function is sufficient. 
See code comment explaining risks assoc.
=> fix: templated string field character escaping

api/views/template-landing.handlebars
None
The link to download a template from Conductor was not working. 
Go to the page for a template in Conductor, click on "Download this template..." and you should get a valid template file.
=> Fix: use template_id rather than project_id for template download

app/src/gui/components/notebook/record_table.tsx
Elana prefers right hand (changing content) to be bolded for UX legibility reasons. 
Minor code change.
=> feat: bold in right hand column

api/.env.dist, api/src/buildconfig.ts, api/src/core.ts
https://jira.csiro.au/browse/BSS-744
Adds configuration in the typical style for rate limit window, events and enable/disable. 
Sets much more generous defaults which evaluate over a longer period. Rate limiting 60 req/minute was excessive - this meant that a request rate of 1/second was too much. This sets it to 1000 requests per 10 minutes which allows for bursty loads while still protecting the API. We would need a more advanced configuration or possibly limiter to catch very high burst loads over shorter durations without punishing normal usage.
=> feat: configurable rate limiting with reasonable defaults

README.md, api/src/api/notebooks.ts, api/src/couchdb/notebooks.ts, api/test/utils.ts, app/.env.dist, app/src/buildconfig.ts, app/src/gui/components/app-bar/app-bar-heading.tsx, app/src/gui/components/notebook/MetadataDisplay.tsx, app/src/gui/components/notebook/index.tsx, app/src/gui/components/record/form.tsx, app/src/gui/components/record/recordStepper.tsx, app/src/gui/components/record/view.tsx, app/src/gui/components/ui/BackButton.tsx, app/src/gui/components/ui/heading-grid.tsx, app/src/gui/components/ui/tab-grid.tsx, app/src/gui/components/workspace/notebooks.tsx, app/src/gui/fields/RandomStyle.tsx, app/src/gui/fields/RichText.tsx, app/src/gui/fields/TakePhoto.tsx, app/src/gui/layout/appBar.tsx, app/src/gui/pages/notebook.tsx, app/src/gui/pages/workspace.tsx, app/src/gui/themes/default/index.tsx
Various UI tweaks in critical views to simplify layouts and fix various bugs. 
Summary of changes: 
- live reload android emulator procedure documented, enabling rapid testing on more realistic device scaling
- rework the survey landing page to unify tabs into single set of tabs, intelligently display required tabs, show arrow icons to enable scrolling with dynamic transitioned width to not waste vertical space when at extremes of tab range, improve component structure/layout, remove truncation of title, remove status icon and remove text from back button
- add dynamic form padding depending on screen size
- increase mobile stepper view section header size and spacing
- remove sync toggle from activated surveys landing page, simplify styling, remove icons, separate into activated and not …
=> feat: upgraded small screen scaling and various UI improvements

app/src/gui/components/ui/BackButton.tsx, app/src/gui/pages/notebook.tsx, app/src/gui/pages/record-create.tsx, app/src/gui/pages/record.tsx, package-lock.json
BSS-718
-As discussed with Elana:
- Added a back button that will take user back to the survey (where records are dispalyed that user has created)
New updates: 
- Used BackButton component to display a back to records button from the record creation phases.
- Improved styling for back button to be displayed  like "back to surveys" button to maintain consistency
- Back button will be displayed like before in record draft view - in wrapped state as previosuly.
- Added android back button effect to detect when user click back button from device, if yes then popup is shown to alert user that there's a draft being saved.
- Back button from record creation also introduces a popup for user to know that there's draft being saved for that record.
- [y ] I have confirmed all commits have been …
=> feat: back button display and intercept to safely alert draft creation

infrastructure/aws-cdk/lib/components/front-end.ts
Fixes missing CSP allowance for image data types on BSS CDK deployment.
=> fix: designer photo rich text field BSS

app/src/context/functions.tsx, app/src/context/projects-context.tsx, app/src/sync/process-initialization.ts, package-lock.json
[BSS-715](https://jira.csiro.au/browse/BSS-715)
Fixes bug in which surveys could not be activated when they had arrived from a refresh survey list update. 
This was due to the `projects_dbs[listing_id]` not being updated during this action. 
This change is stupid and should not be necessary - the issue is that there are now two places in which this data is tracked!! The projects_db in the context management, and also in projects_dbs for the listing. They also have different data structures and data models. 
This whole thing needs a rewrite to unify the project/listing management to a single store. And there is literally no reason for it to be a pouch DB. 
Through code surgery/shenanigans pulls out the logic which syncs the projects_dbs code from the process-initialisation file and reuses …
=> fix: activation of new notebook after refresh

app/src/gui/components/notebook/index.tsx, app/src/gui/components/notebook/overview_map.tsx, app/src/utils/customHooks.tsx
[BSS-749](https://jira.csiro.com/browse/BSS-749)
The overview map would re-render every 10s and reset the  map to the initial position.
- Added 'memo' to the overview map component to prevent re-renders if the props don't change. 
- Added a custom equality comparison to the useRecords query to prevent re-renders if the list of records is the same as last time
- Pass records from the parent into overview map so it doesn't have to get them itself.
View the overview map and zoom/pan the map, note that it doesn't reset after 10s.
=> Fix overview map re-render

app/src/context/projects-context.tsx, app/src/sync/connection.ts, app/src/sync/process-initialization.ts
Fixes critical bug where activated notebooks had `localhost:5984` as their URL due to the `ProjectsObject` being misconfigured. This was introduced in the project activation fix (after refresh) - the issue is that `update_directory` and `get_projects_from_conductor` was doing more work which was not covered by the new logic. 
This adds a `update_directory` call to the syncProjects hook, and removes the previous logic which was overwriting the DB entries with improperly formed data on first initialisation. 
This was masked due to the actual couch DB of a local testing deployment matching the fallback. 
Added error/warning to log outputs to catch this in the future.
=> fix: improper couch DB url due to sync logic

app/src/context/projects-context.tsx
None
Safari doesn't support map.values().filter()
=> Can't filter map values on Safari

web/src/components/data-table/data-table.tsx, web/src/components/dialogs/edit-project-dialog.tsx, web/src/components/forms/update-project-form.tsx, web/src/components/tabs/project/actions.tsx
[BSS-667](https://jira.csiro.au/browse/BSS-667)
Added the ability to edit a project design.
- added edit project dialog
- added update project form
1. Open a project
2. Navigate to the "Actions" tab
3. Click "Edit Project" button
4. Follow the instructions
5. Verify the project has updated (easiest way is likely by downloading the new project file in the edit project dialog)
=> feat: edit project design 🧑‍🎨

web/src/lib/utils.ts
[BSS-794](https://jira.csiro.au/browse/BSS-794)
Resolving the issue where having extra spacing in name would cause the app to crash.
- updated initials function to index the substrings using slice to avoid crashing on empty strings
1. Create a new account with extra spacing in the `name` e.g " Luke  Test "
2. Log in to new conductor using that account
3. Verify the app loads normally and your profile initials are displaying correctly in the bottom left of the screen
=> fix: initials function causing crash 🐞

app/src/gui/components/record/form.tsx, app/src/gui/components/record/formButton.tsx, designer/src/components/form-settings.tsx, designer/src/state/initial.ts, designer/src/state/uiSpec-reducer.ts
[BSS-785
](https://jira.csiro.au/browse/BSS-785)
Introduced the publishbuttonbehaviour configuration setting in "form settings" (Desginer), which will allow users to configure when the publish button should be visible based on the three scenarios. The selected setting is stored in redux and correctly exported to the downloaded JSON of the survey/notebook.
Implemented Scenarios: 
-  Always Show ("always")
The Publish button is always visible, regardless of the form's state.
This is the default behavior for backward compatibility.
-  Show Once All Sections Visited ("visited")
The Publish button only appears when all form sections have been visited at least once.
A section is considered visited when the user navigates to it.
-  Show Only When No Errors Exist ("noErrors")
The Publish button …
=> Publish buttons visibility and configuration

app/src/constants/routes.tsx, app/src/gui/components/notebook/draft_table.tsx
[BSS-830
](https://jira.csiro.au/browse/BSS-830)
This PR fixes an issue where clicking on a draft record in a notebook would lead to a 404 broken link instead of opening the draft.
-  Click on a Ativated survey Survey/Notebook that has drafts.
- If drafts already exist, click on a draft record. It should correctly navigate to the draft page instead of showing 404.
- If no drafts exist, create a new draft
- Click on the newly created draft.
=> Fix broken drafts route

api/src/couchdb/templates.ts, api/test/template.test.ts, app/ios/App/App/Info.plist, app/src/gui/components/notebook/NewNotebookForListing.tsx, app/src/gui/components/record/form.tsx, library/data-model/src/types.ts, web/src/components/forms/update-template-form.tsx
[BSS-824](https://jira.csiro.au/browse/BSS-824)
Fixed bug where template upload was still expecting the `template_name` field (this had been removed in a previous PR).
- updated current uses of `template_name` to use `metadata.name`
- updated template tests not to expect `template_name`
- updated frontend to handle the json without `template_name`
1. Review the backend changes (especially around how template names are defined)
2. In the `/web` platform navigate to a template
3. Test the update template flow in the actions tab
=> fix: import template bug 🐞

app/src/gui/components/record/form.tsx, web/src/components/dialogs/edit-template.tsx, web/src/components/tabs/templates/actions.tsx, web/src/index.css
[BSS-840](https://jira.csiro.au/browse/BSS-840)
Fixed a bug where the page would crash when switching between templates with the action tab open.
- added optional chaining to the prop calls from the data query to avoid error throwing when null
- added disabled prop to button when data has not loaded
1. Navigate to a template
2. Open the actions tab
3. Switch between templates using the sidebar with the actions tab open
=> fix: template actions crash 💥

app/src/gui/component_registry/bundle_components.ts, designer/src/components/field-list.tsx, designer/src/fields.tsx
[BSS-827
](https://jira.csiro.au/browse/BSS-827)
-  Removed the old TextField field type from the field type selection list.
- Ensured onew text field FAIMSTextField are shown in the UI for new field creation.
- Cleaned up conditional logic in view.tsx that handled special rendering for TextField.
- Confirmed that TextField is no longer included in getFieldNames() and the component registry 
- Navigate to designer locally
- cd designer
- npm run start
- http://localhost:5010
- Upload any notebook/survey JSON 
- Navigate to "DESIGN" tab
- Click on "add field button" and from the "Create a new field.. " popup, verify that TextField doesn't exist anymore in that field list.
- New FAIMSTextField is displayed at the top of list (as this is frequently used field in designer)
Screenshots for …
=> Remove designer oldtextfield

app/.env.dist, app/src/gui/components/notebook/datagrid_toolbar.tsx
[BSS-858
](https://jira.csiro.au/browse/BSS-858)
Pr resolves removing "filters" from records table for both "my records" and "drafts" and "other records".
There's a config value added to show /hide filter in my records , drafts, other records tabs.
Please first update the env file at root for this value: 
Config value is - VITE_ENABLE_RECORD_FILTERS, set it to "true" (for BSS) to hide the filters, set it to "false" (for FAIMS) to show the filters.
-Navigate to any survey
- Verify that "filters" is hidden/visible from records table based on config value set -> "My Responses/My Sites etc" and UI is clean.
- Also verify that it's removed/visible from drafts and other records.
SCREENSHOTS:
Before: 
After:
=> remove filters from records table, drafts table.

designer/src/components/Fields/BaseFieldEditor.tsx
[BSS-868](https://jira.csiro.au/browse/BSS-868)
This PR fixes a bug in the BaseFieldEditor where the user could not fully delete or replace the field label. Attempting to delete all characters in the field label input would keep the final character.
- Updated `getFieldLabel` to use `??` instead of `||` operator to allow empty labels.
- Removed the conditional check `if (newState.label)` in `updateFieldFromState` to make sure empty labels are still applied.
1. Create a new field in the editor.
2. In the _Label_ field:
- Type a value (e.g., "Test Field").
- Try deleting the text one character at a time — it should now allow full deletion.
- You should also be able to press Ctrl+A/Cmd+A and delete the whole label or type a completely new one.
3. Confirm that the label updates correctly in …
=> fix: allow field labels to be empty

infrastructure/aws-cdk/lib/components/conductor.ts, infrastructure/aws-cdk/lib/faims-infra-stack.ts
Self explanatory - adds config variables from AWS Secret. CLIENT_ID and CLIENT_SECRET required JSON fields of the secret.
=> feat: enable CDK google oauth configuration

api/src/couchdb/index.ts
When we migrated project db records this changed the name of metadata/data_db to metadata/dataDb. the getMetadata/getDataDb methods are run necessarily **before** migration making them extra sensitive to migration changes. This throws an error (which is good, it's better we error than partially migrate). This PR makes these methods backwards compatible. We will need to identify the 'pre-migration' set of functions that run, and isolate them into a special place in the code so that we can have a check that those methods remain backwards compatible through all future migrations.
=> fix: making db lookup resilient to projects DB migration edge case

infrastructure/aws-cdk/lib/components/front-end.ts, web/src/constants.ts
VITE_APP_URL was added, but there were two issues
1. typo to check API_URL instead of APP_URL in the buildconfig
2. cdk code doesn't include this
=> fix: incorrect API configuration causing /auth-return relative redirect

api/src/api/users.ts, api/test/api.test.ts, library/data-model/src/api.ts, library/data-model/src/data_storage/peopleDB/types.ts, library/data-model/src/permission/types.ts
Adds zod models to the people DB type following the pattern of templates. 
Then specifies the all users list endpoint model by picking props from the base people model. `.strip()` is used to tell zod to pull out extra fields. The res is then parsed at runtime to strip out unwanted props from the DB. 
Unit test added to validate that profiles are not included in user endpoints.
=> fix: removing profiles/hash/salts from users endpoint

api/src/api/notebooks.ts, api/test/api.test.ts, web/src/components/forms/export-project-form.tsx
[BSS-925](https://jira.csiro.com/browse/BSS-925)
The introduction of tokens has broken downloads in control center which relied on cookies to redirect the 
user to the download link.
Introduces a two-step route for downloads of zip/csv data.  First request to /api/notebooks/:id/view.csv returns a redirect response to a URL containing a short lived (5 minute) JWT.   Requesting that URL gives the requested download.
Imlemented for zip and csv downloads here but can be extended to other download types.
Try exporting data from a notebook in the Control Center.
=> Fix Data Export from Control Centre

designer/src/components/Fields/BaseFieldEditor.tsx, designer/src/components/Fields/OptionsEditor.tsx, designer/src/components/debounced-text-field.tsx
[BSS-917](https://jira.csiro.au/browse/BSS-917) - **Designer: editing help text reverts other changes in a field**
[BSS-898](https://jira.csiro.au/browse/BSS-898) - **Remove debounce on designer option select input**
This pull request addresses some performances issues with DebouncedTextField and fixes issues where field changes could be lost. This effectively resolves **BSS-917,** an issue where editing help text was reverting other changes in a field.
Also, DebouncedTextField usage has been removed the OptionsEditor component.
- Rewrote the DebouncedTextField component.
- Reduced default debounce text field time from 500ms -> 200ms.
- We now flush the debounce function instead of cancelling it to prevent data loss.
- Updated debounce function from a _useRef_ to _useMemo_, so it is not …
=> fix: DebouncedTextField Improvements, fix help text changes reverting other field changes

app/src/gui/components/map/center-control.tsx, app/src/gui/fields/RichText.tsx, app/src/gui/fields/checkbox.tsx, app/src/gui/fields/fieldWrapper.tsx, app/src/gui/fields/maps/MapWrapper.tsx, app/src/gui/fields/radio.tsx, web/src/routes/_protected/profile.tsx
[BSS-798 
](https://jira.csiro.au/browse/BSS-798)
This PR resolves the issue where the word "Error" was being displayed in place of the damage rating helper text when the field content was empty.
Upon investigation, it was found that the helper text field was using a RichTextField component to render static content. When the content string was empty, the component still attempted to render, resulting in "Error" being displayed instead of simply showing nothing.
Fix: 
Added a condition to prevent RichTextField from rendering if the content is empty or null, also empty helper text fields render cleanly without unnecessary placeholder or fallback text.
Open Designer at http://localhost:5010 and upload a JSON with RichText helper text (empty and non-empty cases).
Added a JSON for reference …
=> Major Bug : Fix damage rating helpertext.

app/src/gui/components/authentication/shortCodeOnly.tsx, app/src/gui/pages/shortcode.tsx, app/src/utils/helpers.tsx
https://jira.csiro.au/browse/BSS-919
Replaces existing OR appends instead of blindly appending. This will always force a prioritisation of the app's preferred redirect. 
There could also be scope to prevent putting the redirect in in the first place (when generated from the control center) - relying on the API to have reasonable defaults - but this is harder as it would require inspecting the invite more thoroughly and determining a URL intelligently from that. 
This should fix this bug at least. 
Generate a team invite code in control center. Scan it on a mobile device. Ensure it opens, registers, then redirects back. 
@stevecassidy  hoping you can test on mobile.
=> fix: qr scan of code with existing redirect causes double redirect

api/README.md, api/src/couchdb/index.ts, api/src/scripts/migrate.ts, localdev.sh
Makes the application of key configuration from the local .env into the deployment an opt in --keys flag rather than default behaviour. The reason for this is that in deployed prod environments, it is hard or even impossible for the local environment to match the key configuration of the deployed environment, and migration is really about database migration in this context.
=> fix: optional key configuration push for npm run migrate

web/src/components/dialogs/edit-project-dialog.tsx, web/src/components/forms/create-project-from-template.tsx, web/src/components/tables/cells/team-cell.tsx, web/src/components/tables/cells/template-cell.tsx, web/src/components/tabs/project/actions.tsx, web/src/routes/_protected/profile.tsx
https://jira.csiro.au/browse/BSS-901 (team selector missing in create survey from template form)
Fixed by adding selector
https://jira.csiro.au/browse/BSS-902 (Download JSON action from control center adds additional fields causing designer parse fail)
Fixed by explicitly unpacking response into proper format
https://jira.csiro.au/browse/BSS-903 (Permission error fallback for template column of surveys)
Fixed by updating Team and Template cell component to show the ID and disable clicking link/link styling if the value cannot be fetched. This could be more sophisticated but this prevents bad states/missing data for now.
https://jira.csiro.au/browse/BSS-901 (team selector missing in create survey from template form)
Try creating survey from template and check team works. …
=> fix: misc web fixes

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
None
Adds configuration for devcontainer for vscode.
This devcontainer config will create a pair of docker containers to allow working with the project in a
standardised environment.    It creates a couchdb container and a workspace container that can 
be used to run the other services.   A minimal set of environment settings suitable for development
are included in the config.  
This can be ignored if you prefer another environment.  Having this in the repo enables opening the repo
or a pull request in an isolated volume (https://code.visualstudio.com/docs/devcontainers/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume).   
On MacOS this helps because it puts the code inside the container in a volume which is much faster than bind mounting
a local …
=> Add Devcontainer Config for VSCode

package-lock.json, web/src/components/session-expired-overlay.tsx, web/src/constants.ts, web/src/context/auth-provider.tsx, web/src/routes/_protected.tsx
If you load /web on a cold load with an expired refresh token, the app does not recover from this state until it is forcefully refreshed. This was due to the following sequence
1. _protected route before load sees isAuthenticated true (since it was the last state of the app before close)
2. this causes it to return the child route - the child route throws a bunch of errors as isAuthenticated is incorrect
3. meanwhile, the auth context provider asynchronously refreshes - this refresh fails, and isAuthenticated is set to false
4. **_protected before load does not rerun!** - so this state is never picked up
The solution here was to add a splashscreen over the actual component code when isAuthenticated, as part of the react lifecycle. This will be caught with a re-render appropriately. It …
=> fix: web cold load auth

app/.env.dist, app/src/buildconfig.ts, app/src/gui/components/record/RecordData.tsx
https://jira.csiro.au/browse/BSS-958
https://jira.csiro.au/browse/BSS-965
Default hides the links feature on the existing record data page - use `VITE_SHOW_RECORD_LINKS='true'` in the /app environment to enable it. Also tidies up/documents the conditions a bit for loading vs hiding etc.
=> feat: control links feature with config variable

api/src/api/notebooks.ts, app/src/context/slices/projectSlice.ts, app/src/gui/components/metadataRenderer.tsx, app/src/gui/components/notebook/MetadataDisplay.tsx, app/src/gui/components/notebook/NewNotebookForListing.tsx, app/src/gui/components/notebook/settings/sync_switch.tsx, app/src/gui/components/workspace/notebooks.tsx, app/src/gui/layout/appBar.tsx, app/src/gui/pages/notebook.tsx, app/src/gui/pages/record-create.tsx, app/src/gui/pages/record.tsx, library/data-model/src/api.ts, web/src/components/tabs/project/details.tsx, web/src/routes/_protected/projects/$projectId.tsx
https://jira.csiro.au/browse/BSS-921
Improving handling of names for projects by exposing and respecting project.name instead of project.metadata.name.
Updates the API to return the project.name which is already being handled correctly. 
Updates the clients (web and API) to use this name rather than metadata.name. Also updates the redux store to expose Name directly, and merge it from API.
Make a notebook, check it works. Update it using web (can be the same file, that's fine), check that the name stays as the explicitly set name not the notebook metadata name. 
We should improve this in the long term by removing the metadata DB and just having one place where this is configured. The specification name and the project name do not need to be/nor should be related.
=> fix: project names change after edit

app/src/gui/components/record/RecordData.tsx, app/src/gui/components/record/form.tsx, app/src/gui/components/record/formButton.tsx, app/src/gui/components/record/recordStepper.tsx, app/src/gui/pages/record-create.tsx, app/src/gui/pages/record.tsx, app/src/utils/generateStepperColors.tsx
https://jira.csiro.au/browse/BSS-963
Adds a flag 'isExistingRecord' as prop to form.tsx. On mount, if it is an existing record, tells the stepper that all sections have been visited and that the form should try to validate. Also removes all special conditional formatting in the stepper which prevented showing proper colors when it was an existing record. Also made the formatting more obvious for which section is active.
Publish a form with multiple sections and errors. Go back to the record, you should see all sections have appropriate errors visible.
=> fix: remove stepper edge case for existing records by forcing all sections to be viewed

api/src/couchdb/notebooks.ts
[BSS-939](https://jira.csiro.com/browse/BSS-939)
Enables escaping formulas to avoid CSV injection attacks.
Enter data in a notebook cell starting with =, value should be quoted (\=) in csv export.
=> Enable escaped formulas in CSV export

app/src/constants/routes.tsx, app/src/gui/components/notebook/add_record_by_type.tsx, app/src/gui/components/notebook/draft_table.tsx, app/src/gui/components/notebook/overview_map.tsx, app/src/gui/components/notebook/record_table.tsx, app/src/gui/components/record/confirmExitDialog.tsx, app/src/gui/components/record/conflict/conflictfield.tsx, app/src/gui/components/record/fields.tsx, app/src/gui/components/record/form.tsx, app/src/gui/components/record/formButton.tsx, app/src/gui/components/record/recordStepper.tsx, app/src/gui/components/record/relationships/RelatedInformation.tsx, app/src/gui/components/record/relationships/create_links/create_record_link.tsx, app/src/gui/components/record/relationships/field_level_links/datagrid.tsx, app/src/gui/components/record/relationships/parent_form.tsx, app/src/gui/components/record/relationships/parent_panel.tsx, app/src/gui/components/record/relationships/types.tsx, app/src/gui/components/record/view.tsx, app/src/gui/components/workspace/notebooks.tsx, app/src/gui/fields/RelatedRecordSelector.tsx, app/src/gui/fields/maps/MapWrapper.tsx, app/src/utils/generateStepperColors.tsx, package-lock.json
This is due to formik refusing to run onSubmit when there are form errors. The RelatedRecordSelector relied on this behaviour (hence probably why old FAIMS folk instead chose to **sneakily** disable adding a child record until all errors are gone - good one!!). Instead we pass through 'forceSave' which bypasses this check. Very gross approach but it's the smallest intervention to fix the problem.
=> fix: cannot add child records when there are form errors

app/src/gui/components/map/map-component.tsx, app/src/gui/components/map/tile-source.ts
None
Logs failed map style cache hits and shows them in the UI to help debugging blue line maps.
=> Add a log of failed cache URLs to map component

app/src/gui/components/notebook/settings/auto_incrementers.tsx
None
When there is more than one auto incrementer field in a notebook, the settings button opened all
settings dialogs at once so only the last auto incrementer could be changed.
This PR fixes this by factoring out the button open/close status to a separate component.
=>  Fix Autoincrementer settings buttons

api/notebooks/sample_notebook.json, api/src/couchdb/notebooks.ts, api/test/api.test.ts
[FAIMS1515](https://github.com/FAIMS/FAIMS3/issues/1515)
Current CSV export ignores annotation and uncertainty on fields.  This PR includes them in the export.
Any field with annotation or uncertainty enabled will get an extra column in the CSV export called FFFF_AAAA  where FFFF is the field id and AAAA is the defined annotation (or uncertainty) label.  The content will be the value of the annotation or uncertainty on that field.
Export data from a notebook that has annotation and uncertainty added.
=> Include annotation and uncertainty in csv export where enabled

app/bin/prebuildConfig.sh, web/.env.dist, web/.gitignore, web/src/components/logo.tsx, web/src/constants.ts, web/src/index.css, web/src/lib/theme.ts, web/src/main.tsx
[1516](https://github.com/FAIMS/FAIMS3/issues/1516)
Add theming for the control centre app.
Theming selected by the same setting as the app, VITE_THEME is default (Fieldmark) or bssTheme.  
Currently minimal theming since there isn't much styling in the app.
Configure with:
VITE_THEME=bssTheme
VITE_THEME=default
Run build from the top level to generate the icon assets in the web folder.  Then run the control centre to see the new theme.  
BSS theme is the same but uses the same icon as the app.   Default theme uses the Fieldmark icon.
=> Control Centre Theming

web/src/designer/components/Fields/BaseFieldEditor.tsx, web/src/designer/components/Fields/OptionsEditor.tsx, web/src/designer/components/condition.tsx, web/src/designer/components/condition/ConditionControl.tsx, web/src/designer/components/condition/ConditionModal.tsx, web/src/designer/components/condition/ConditionTranslation.tsx, web/src/designer/components/condition/constants.tsx, web/src/designer/components/condition/types.tsx, web/src/designer/components/condition/utils.ts, web/src/designer/components/field-editor.tsx, web/src/designer/components/form-editor.tsx, web/src/designer/components/section-editor.tsx
[Designer: Multi-select in condition editor should use checkboxes](https://github.com/FAIMS/FAIMS3/issues/1503)
This PR introduces checkboxes to the multi-select value selector in `FieldConditionControl`. When editing a condition where the target field is a multi select, the possible menu options will now appear as checkboxes.
The lengthy `condition.tsx` file has also been broken up into separate files.
- Open Designer in Control Centre by editing a template or project.
- Create a multi-select field.
- Create another field, and create a condition on it.
- Select the multi-select field as the target of the condition.
- The value options popup should contain selectable checkboxes that successfully modify the condition.
=> feat: Multiselect checkboxes condition editor

web/src/components/form.tsx, web/src/components/forms/create-project-invite.tsx, web/src/components/forms/teams/create-team-invite-form.tsx
None
Seeing a crash bug in control center when creating a team invite.   Was evident in production build, not seen in development.
Team invite form is computing the role options on each render which is somehow causing an infinite recursion. Here we useMemo to ensure they are only computed once for each user/team combination.    Also made the same change
to the project invite form.
Also noted a warning in the console about controlled inputs in forms.  Fixed this by ensuring that form input values don't become undefined. 
Create an invite for a team or project in control centre.
=> Web Form Fixes

api/package.json, api/src/couchdb/backupRestore.ts, api/src/scripts/restoreBackup.ts, api/test/api.test.ts, api/test/backup.test.ts, app/src/sync/data-dump.ts, docs/developer/docs/source/markdown/Backup.md, library/data-model/src/data_storage/dataDB/design.ts, library/data-model/src/data_storage/utils.ts, library/data-model/tests/data_storage.test.ts
None
Following a failure in trying to restore a large backup, this PR has some changes to improve both the backup and restore processes.
Update the on-device backup process to use low-level methods to get the databases to dump containing records.  This prevents a problem we've seen recently where the backup failed because (we think) the internal data structures referencing databases were broken.  To avoid this in future, since this is an emergency procedure, we just look at the low level IDB database names to find dataDBs to back up.
For restoring backups, there was a memory leak that prevented large backups being restored.  I don't think it was a genuine leak but due to the rapid reading and writing of records, the GC did not catch  up and heap memory was exceeeded.  Here we add a batch …
=> Improved Backup and Restore

app/src/gui/components/notebook/record_table.tsx, app/src/gui/components/record/conflict/conflictform.tsx, app/src/gui/components/record/relationships/RelatedInformation.tsx, app/src/gui/components/record/relationships/create_links/create_record_link.tsx, app/src/gui/components/record/relationships/field_level_links/datagrid.tsx, app/src/gui/fields/RelatedRecordSelector.tsx, app/src/gui/pages/record.tsx
[BSS-973
](https://jira.csiro.au/browse/BSS-973)
This PR revives the old feature/child-records-table branch, rebases it onto the latest develop, and resolves all conflicts, then realigns the child-record DataGrid with the styling and behaviour of the main RecordsTable. 
Have kep the vehicle record id included in field id for better reference, rest all is aligned with main records table, have additional actions column  as before that allows "remove link".
The column set is now identical—Record is renamed Field Id, date/user metadata columns are in the same order, and the shared helpers buildColumnFromSystemField and buildVerticalStackColumn are reused to eliminate duplicate logic.
Create a parent record which includes related record selector like  - Structure and Assets 
Attached test …
=> clean + fix old branch, enhancements for related record child record tables

api/src/auth/authRoutes.ts, api/views/auth-legacy.handlebars, app/.env.dist, app/src/buildconfig.ts, app/src/sync/initialize.ts
None
Users of the v1.0 app would need to reset devices to use the new app and would lose any data on device that was not synced.
Adds a placeholder page at /auth on conductor with a message about updating the app, this should catch any existing users who try to login with the old app.
Adds a migration in the app to rename any existing dataDbs to use the new name format.   The old database is then deleted.  This means that when the user re-activates the notebook, they will see whatever data was present before the update without having to sync.  This should include any data on device that had not been synced before.
Complex to test.   Set up a v1.0.0 server and create a notebook, create some records, activate the notebook in the app and sync.   
Shut down the v1.0.0 server. Run migrate from …
=> Facilitate migration from v1.0

api/src/api/notebooks.ts, api/src/couchdb/notebooks.ts, api/test/teamIntegration.test.ts, library/data-model/src/api.ts, library/data-model/src/permission/model.ts, library/data-model/tests/permissionfunctions.test.ts, web/src/components/dialogs/add-project-to-team-dialog.tsx, web/src/components/forms/add-project-to-team-form.tsx, web/src/components/forms/export-project-form.tsx, web/src/components/tabs/project/actions.tsx, web/src/hooks/project-hooks.ts
None
As I migrate Fieldmark to the new version I need to assign existing notebooks to teams.  There is currently no
way to do this.
Add an action in control center to assign a notebook to a different team. 
Also adds a quick fix - the drop-down for export was using viewset names rather than labels.
View  a notebook actions tab. If you have permission (project manager/admin) you will see the
new dialog. Teams shown in the drop down are those that you are a member of.
=> Assign a project to a new team in Control Center

web/src/routes/__root.tsx
#1591 
Currently the control centre shows a generic error page when we crash with no user actions.
Adds a custom error component with a link back to the home page which should resolve most problems.
TODO: integrate bugsnag...
Create an error (add some random code) and see the page.
=> Adds an error component to show a nicer page when we crash

web/src/designer/components/Fields/BaseFieldEditor.tsx, web/src/designer/components/Fields/BasicAutoIncrementer.tsx
[#1584](https://github.com/FAIMS/FAIMS3/issues/1584)
In the editor, an AutoIncrementer field displays only it's label which is not used anywhere, the ID is not visible. If a user changes the label they lose track of what the ID is if they want to add it to a templated field.
Use the BaseFieldEditor for this field to allow label visibility and editing but configure it to hide the parts we don't need.
In the designer, create an AutoIncrementer field.
=> Make field name visible in AutoIncrementer

app/src/gui/components/map/map-download.tsx, app/src/gui/components/map/tile-source.ts
None
Two issues:
- bugsnag reports an error with toSorted in older browsers not being supported
- downloaded map list on mobile is below the map and offscreen so not visible
- Use .sort to sort the list of maps downloaded. 
- Put the downloaded map list in an accordion, closed by default but above the map view so it is visible. Open it when downloading.
Check out the offline map component.
=> Offline maps tweaks and fixes

app/src/gui/fields/TakePhoto.tsx
#1631
Various user actions were being logged to BugSnag that we don't need to know about when the user cancelled the camera app or denied location permissions. 
Don't log these 'errors'.  User will still be notified.
Cancel the camera app in a take-photo field.
=> Remove logerror when user closes camera app etc.

app/capacitor.config.dist.json, app/src/App.tsx
None
In the mobile app, the display is still overlapping the safe-area at the top of the screen unless you turn the device sideways and back again.
Initialise the safe-area plugin in code rather than in config seems to fix the problem.
Build for IOS/Android, open the app. You should see that the app does not overlap the safe area.
=> Initialise safe-area plugin in code rather than in config

app/src/gui/components/notebook/record_table.tsx, library/data-model/src/data_storage/queries.ts
#1635 
Filtering and sorting is broken for 'summary fields' in the records table and search only sometimes works.  
The problem was with the way that summary field values in the table were generated, we used renderCell which meant that the value that was being sorted/filtered was not what was shown.   Replace this with valueGetter to return a string value.   This then re-enables sort and filter in the table. 
Search didn't work on values that were arrays. Modified the query to use a regex within arrays as well as for plain values.
In the record table for a notebook with configured summary fields, click on a table header to sort. Use filters via the table header. Search via the search box.
=> Fix record sort and filter

api/src/couchdb/emailReset.ts, api/src/couchdb/index.ts, api/src/couchdb/longLivedTokens.ts, api/src/couchdb/notebooks.ts, api/src/couchdb/refreshTokens.ts, api/test/mocks.ts, app/src/context/slices/helpers/databaseHelpers.ts, app/src/context/slices/helpers/databaseService.ts, app/src/context/slices/helpers/pouchDBWrapper.ts, app/src/context/slices/projectSlice.ts, app/src/index.tsx, app/src/sync/data-dump.ts, app/src/sync/draft-storage.ts, docs/user/conf.py, library/data-model/src/data_storage/authDB/types.ts, library/data-model/src/data_storage/internals.ts, library/data-model/src/data_storage/invitesDB/types.ts, library/data-model/src/data_storage/migrations/migrationService.ts, library/data-model/src/data_storage/migrationsDB/types.ts, library/data-model/src/data_storage/peopleDB/types.ts, library/data-model/src/data_storage/projectsDB/types.ts, library/data-model/src/data_storage/storageFunctions.ts, library/data-model/src/data_storage/teamsDB/types.ts, library/data-model/src/data_storage/templatesDB/types.ts, library/data-model/src/data_storage/utils.ts, library/data-model/src/types.ts, library/data-model/tests/migrationService.test.ts, library/data-model/tests/mocks.ts
#1632
We are seeing intermittent failures of IndexedDB in IOS webview due perhaps to a bug.   It seems that one way around this is to re-open the database connection should it ever disappear.  
Adds PouchDBWrapper in the app to act as a wrapper class for all database connections, mimicing the 
PouchDB.Database interface.   All methods are passed through a retry method that will re-open 
the database connetion if required, up to three times.   
In the normal course of things, this is a no-op wrapper.  Should the connection fail, it will re-open the
connection and try again.  We'll get a logError in this case to see that it is happening. 
Should have no effect on operation unless this bug hits.  All tests pass and it seems to work in casual testing.
=> Add wrapper around PouchDB in the app to intercept connection failures

app/src/context/slices/helpers/pouchDBWrapper.ts
None
Reduce logging of connection recreation - we know this works. Only log failure to recreate.
=> PouchDB Wrapper: only log on failure to recreate connections
